### ISSUE TITLE
compile mobile build using data.zip from pc?

### ISSUE THREAD

**Issue by funnynnuf** [TerryCavanagh/VVVVVV#1001]
i would like to do this but idk if i can compile using data.zip from pc (gog ver)
my main account is @SirGamers btw

**Comment by InfoTeddy** [comment]
No, you cannot. Mobile has a separate data file which can be found [here](https://thelettervsixtim.es/makeandplay/).

**Comment by funnynnuf** [comment]
> No, you cannot. Mobile has a separate data file which can be found [here](https://thelettervsixtim.es/makeandplay/).

so only make and play for mobile can be compiled?

**Comment by InfoTeddy** [comment]
No, you will be able to compile the full build. M&P doesn't exist on mobile.

**Comment by funnynnuf** [comment]
OHHHHHH so the data.zip on the website is full game ok
