### ISSUE TITLE
the data package should be properly versioned

### ISSUE THREAD

**Issue by pirate486743186** [TerryCavanagh/VVVVVV#1006]
right now, there's no way of knowing if the data were updated or not, short of downloading the whole thing. And there's no way of getting notified that they changed.

A github repo would be very convenient and allow for a push notification (github just sends you an email) instead of scrapping a webpage every know and then.

**Comment by InfoTeddy** [comment]
I personally didn't like that we updated data.zip and hope it doesn't ever happen again. I think the downstream Nix build broke because of it too, lol.

We are not going to make a GitHub repository because we do not want any more changes to data.zip.

**Comment by flibitijibibo** [comment]
To confirm: data.zip is locked down and the current sha256 from the official build should be considered the last version. If we make changes or add new files we'll add new zip files and mount them via PhysFS to take priority over the outdated assets, should any updates occur (it'll likely just add _new_ files, if anything).
