### ISSUE TITLE
GameCube controllers use swapped glyphs

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#1011]
All non-Joy-Con controllers with Nintendo's VID use `LAYOUT_NINTENDO_SWITCH_PRO`. For GameCube controllers (057e:0337) this is incorrect, with issues like A and B being swapped.

**Comment by flibitijibibo** [comment]
Shoot, I probably need to set USE_BUTTON_LABELS=0 or something...

**Comment by flibitijibibo** [comment]
Should have a commit tomorrow that just sets the hint, but to confirm: Does setting SDL_GAMECONTROLLER_USE_BUTTON_LABELS=0 fix the issue for this device?

**Comment by leo60228** [comment]
It does not. I'm not sure "north/south/east/west correctness" is actually meaningful here, since the GameCube controller does not have the buttons arranged in a diamond shape like most controllers do.

**Comment by flibitijibibo** [comment]
Hmm, I think I understand a bit more - does adding a check for the GameCube product ID fix it? We can probably just use Xbox for now (maybe Generic if we want to avoid color coding?), though if we have space I suppose it'd be cool to add GameCube bitmaps...

**Comment by leo60228** [comment]
Yes.

**Comment by flibitijibibo** [comment]
Alrighty, if nobody beats me to it I'll add this check in the morning.

**Comment by flibitijibibo** [comment]
https://github.com/TerryCavanagh/VVVVVV/commit/c881f621a3f719b3b125f86f9af8c6c894eac92f
