### ISSUE TITLE
Migrate Save files/player levels on OSX

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#102]
VVVVVV 2.0 failed review on the Mac App Store because it stores saves and player levels in the ~/Documents folder, which is fair enough. But due to time constraints at the time, we launched on Humble/Steam with the ~/Documents folder on OSX. This now leaves VVVVVV with a complicated situation on Mac:

 - Saves should be in ~/Library/Application Support
 - Many people on mac will have their saves from 2.0 in ~/Documents, and the game will need to scan that folder at startup and migrate them for a potential 2.3 update, and delete the old save folder.

**Comment by flibitijibibo** [comment]
I believe this handles all of that (the PhysFS save path is in Application Support):

https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/src/FileSystemUtils.cpp#L214

**Comment by TerryCavanagh** [comment]
Ahha! How did I miss that this had already been done! I've had this in the back of my mind for the past 9 years 😅 

Right, well, closing!
