### ISSUE TITLE
Consider moving the language selection to the main menu

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/VVVVVV#1021]
It's the main selling point of the next update, and it's currently a little hidden.

**Comment by Daaaav** [comment]
To be fair, when 2.4 is started and a language hasn't been set before, the game shows the language screen before showing the main menu.

**Comment by TerryCavanagh** [comment]
Yep, the update will display the language selection screen at startup, so this should be ok. Closing!
