### ISSUE TITLE
wait what????

### ISSUE THREAD

**Issue by SirGamers** [TerryCavanagh/VVVVVV#1026]
"You'll need the data.zip file from VVVVVV to actually run the game! It's available to download separately for free in the [Make and Play](https://thelettervsixtim.es/makeandplay/) edition of the game. Put this file next to your executable and the game should run."
if i were to build the game then use my gog data.zip it would be make and play?????
cuz I just realized that the game data is hard coded into the exe cuz I swapped my real data.zip for m&p data.zip and the game still booted the full thing i also swapped my m&p data.zip with my main data.zip for m&p but it still opened make and play

**Comment by InfoTeddy** [comment]
There are no differences in `data.zip` between M&P and the full game. Assets in `data.zip` are not hardcoded into the executable.

**Comment by SirGamers** [comment]
> There are no differences in `data.zip` between M&P and the full game. Assets in `data.zip` are not hardcoded into the executable.

but would it be m&p if I compiled it and used full game data.zip

**Comment by InfoTeddy** [comment]
If you don't compile it as M&P, then it won't be M&P. `data.zip` has nothing to do with whether the build is M&P or not.

I agree that the wording on the page can be confusing though.

**Comment by Daaaav** [comment]
M&P or not is determined at compile-time, depending on whether the `MAKEANDPLAY` define was set (see `MakeAndPlay.h`).

**Comment by SirGamers** [comment]
> If you don't compile it as M&P, then it won't be M&P. `data.zip` has nothing to do with whether the build is M&P or not.
> 
> I agree that the wording on the page can be confusing though.

ima clarify using the power of prs

**Comment by SirGamers** [comment]
> M&P or not is determined at compile-time, depending on whether the `MAKEANDPLAY` define was set (see `MakeAndPlay.h`).

thx

**Comment by SirGamers** [comment]
> depending on whether the `MAKEANDPLAY` define was set.

if its not set, its not m&p right?

**Comment by Daaaav** [comment]
Correct.

**Comment by SirGamers** [comment]
> ima clarify using the power of Pull Requests
#1027
