### ISSUE TITLE
Mouse cursor shows in full screen mode on the Raspberry Pi

### ISSUE THREAD

**Issue by pjft** [TerryCavanagh/VVVVVV#105]
Just thought I'd raise this. It's probably related to #15 as when I compiled it 8 days ago it didn't.

For now, I'm happy to just revert the change on my end when I build, but thought I'd raise it.

Keep up the great work!

**Comment by flibitijibibo** [comment]
Might be an SDL issue? We don’t reveal the cursor unless focus is lost, and SDL handles that.

**Comment by parkerlreed** [comment]
I'm seeing this on Arch Linux as well (Both desktop and ARM)

sdl2 2.0.10-1

The cursor does get moved to the upper left, but is not hidden. 

![image](https://user-images.githubusercontent.com/841440/72921139-b39ad680-3d18-11ea-821b-2ba72acd7104.png)

This happens 100% of the time on the ARM device but only sometimes on desktop. The alternate behavior on desktop is getting moved to somewhere towards the middle of the screen but still not hidden.

![image](https://user-images.githubusercontent.com/841440/72921302-07a5bb00-3d19-11ea-83f7-fe681435720d.png)

**Comment by flibitijibibo** [comment]
Oh, totally missed that. So yeah, we'll need to add a setting for that.

**Comment by pjft** [comment]
Apologies for the delay. Correct, it was re-enabled on #15 .
