### ISSUE TITLE
Do a quick refresh of the github repo readmes for 2.4

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#1052]
Not that important, but was reading over some of them and noticed that they could do with a bit of an update (they still have warnings about compiler quirks that are no longer applicable, for example).

**Comment by TerryCavanagh** [comment]
Ok, done! You can view the changes in this branch, feedback welcome:

https://github.com/TerryCavanagh/VVVVVV/tree/repo-refresh-for-2.4

I'll set it live with feedback applied once 2.4 launches.

**Comment by Daaaav** [comment]
- The table in [License exceptions.md](https://github.com/TerryCavanagh/VVVVVV/compare/master...repo-refresh-for-2.4?short_path=a542883#diff-a5428837e7a302e1232e202f133ea350790f253f15723edace1fe25c5001a361) went from 5 to 3 columns:
![Project | Creator | Description | Conditions | Link → Project | Description | Conditions](https://github.com/TerryCavanagh/VVVVVV/assets/44736680/95dfc5a2-5482-4e4e-941d-455eb46b7792)

- Personally I'm not sure about removing the last paragraph in [desktop_version/README.md](https://github.com/TerryCavanagh/VVVVVV/compare/master...repo-refresh-for-2.4?short_path=a542883#diff-74f95ad93762dad33ab165b955f21f060155ce1bea90bd198dea269449933d03) (about data.zip being for personal use only). That's probably too much of a "what if someone misses the other places and dove straight into desktop_version to compile the game" on my part, but thought I'd mention it anyway.

**Comment by TerryCavanagh** [comment]
Thanks! I've fixed the table, and I agree that we should probably keep the note at the end of that readme, so I've reverted that change.

**Comment by TerryCavanagh** [comment]
Done!
