### ISSUE TITLE
Localization notes for Brazillian Portuguese

### ISSUE THREAD

**Issue by Space-G** [TerryCavanagh/VVVVVV#1064]
I found that most of my notes are about references that were translated differently than their original title.

---

| Original Name | Current translation | Suggested translation | Reasoning |
| --------------|-------------------|----------------------| --- |
| Gantry and Dolly | Pórtico e Dolly | Grua e (Trilhos \| Carro \| Vagão \| Carrinho)| Aesthetics, and personally less confusing but this one is abstract |
| V Stitch | Ponto V | Costura V | Keeps the meaning, reduces ambiguity. Avoids confusion with "G Spot" (Evita assimilação a "Ponto G" mantendo o significado) |
| The Tomb of Mad Carew | A tumba de Mad carew | A tumba de Mad Carew | Capitalization (Capitalização) |
|~~As You Like It~~| ~~Como gostais~~ | ~~Como você gosta~~ | ~~More close to how humans actually speak nowadays~~ The localization is correct |
| Shockwave Rider | Cavaleiro Shockwave | Shockwave Rider | Keeps the reference to the book that wasn't released in portuguese (Mantém a referência ao livro de título Shockwave Rider) |
| On the [VW]aterfront | À [bv]eira-mar | Sindicato de La[dv]rões OU [VS]indicato de Ladrões | Keeps the reference to the movie, using it's released title here (Mantém a referência ao filme On the Waterfront) |
| ~~Vwitched~~ | ~~V Feiticera~~ | ~~Vwitched~~ | ~~Although Bewitched (the sitcom) is a great reference, I believe it was originally a reference to the Bwitched girl group (Embora A Feiticeira seja uma ótima referência, muda o significado original, que é a referência à Girl Group Bwitched)~~ The localization is correct |
| The Voon Show | O show de voons | The Voon Show | Keeps the reference to the british radio show (Mantém referência ao show humorístico de rádio The Voon Show) |
| The 9 O'Clock News | Notícias das 9 horas | Jornal das 9 | "Jornal" instead of "notícias" because that's how we call the program that shows the news on TVs and Radios. It's also what "newspaper" is called. The omission of the word "horas" (hours) is due to how we refer to programs in radios and television. (O jornal é autoexplicativo, a omissão da palavra "horas" reflete o jeito comum de falar sobre programas de televisão.) |
| Panic Room | Sala de Pânico | O quarto do pânico | Keeps the reference to the 2002 movie, using it's released pt-br name (Mantém a referência ao filme Panic Room, cujo nome em pt-br é O quarto do pânico) |
| Cosmic Creepers | Trepadeiras cósmicas | Crepúsculo Cósmico | Is the name of the cat in the brazillian dubbed version of Bedknobs and Broomsticks, keeping the original reference. (É o gato da bruxa aprendiz Eglantine Price, no filme Se a minha Cama Voasse, dublado em pt-br.) |
| The Sensible Room | A sala sensível | A sala sensata | It's a false cognate*  |
| Brass sent us under the top | Bronze nos enviou abaixo do topo |  O alto comando nos enviou | Translates "Brass" as the metal, instead of the military slang* |
| Vertigo | Vertigem | Um Corpo que Cai | Vertigo translates correctly, but the movie had a different title in PT-BR* |

\* noted by [@zaratustra on Cohost](https://cohost.org/terrycavanagh/post/3679724-vvvvvv-localisation#comment-83e4547c-5c31-4d1f-8a4e-9177eddeae30)

----

**Comment by Fussmatte** [comment]
On the "Vwitched" thing: Bennett Foddy confirmed that it was a reference to the sitcom. In turn, the likely intended pronunciation is "vee-witched". See https://vsix.dev/wiki/Room_name_explanations#The_Final_Level

**Comment by Space-G** [comment]
> See https://vsix.dev/wiki/Room_name_explanations#The_Final_Level

I wasn't aware of this resource, thank you!

I've changed the original post to cross out what was correctly localized originally.

**Comment by TerryCavanagh** [comment]
These have not come back in time for 2.4, but I'll poke our PTBR translators about addressing them for 2.4.1.

**Comment by Space-G** [comment]
I can do it if you'd like me to.

Only reason I haven't yet is 'cause a teacher once said that I should ask permission before working on OSS... 

Do I have permission?

**Comment by TerryCavanagh** [comment]
Thank you, but only the translators can approve changes to the translations!

**Comment by TerryCavanagh** [comment]
... actually, never mind - a pull request would be very much appreciated, thank you!
