### ISSUE TITLE
localization: toki pona (tok)

### ISSUE THREAD

**Issue by sporksmith** [TerryCavanagh/VVVVVV#1078]
> It *is* possible to make a fan translation for fun, for sharing with others, etc. But it probably won't be distributed with the game officially.

I'm tinkering with doing this for toki pona :). As you suggest I don't have any expectation that it'll get merged, but figured I'd drop an FYI.

Here's the branch I just started: https://github.com/sporksmith/VVVVVV/tree/toki-pona

From [Sonja Lang's official site](https://tokipona.org/):

> Toki Pona is a human language I [Sonja Lang] invented in 2001. It was my attempt to understand the meaning of life in 120 words. There are now thousands of speakers and 137 essential words. In 2022, ISO 639-3 adopted the code "tok" for Toki Pona, which it categorized as a world language. Toki Pona is among the [most popular conlangs](https://tokipona.org/largest_conlangs.html) online.

I'm not an expert in toki pona, though who knows maybe I'll end up getting some interest from experts to help out. This is just a fun exercise and side-project for me.

**Comment by Daaaav** [comment]
One technical note:

> [Generate toki pona language files](https://github.com/sporksmith/VVVVVV/commit/68f68eb6c3d08b6ce7db05e5901f58d3bf9c5942)
> Generated in-game using the translator tools.

The in-game sync tools aren't really meant for generating initial versions of the language files - just for syncing changes from English to existing language files - but it _almost_ works to create fresh files for a new language. You're just missing `numbers.xml`, and also, `meta.xml` was filled with details from a random language. So you'd still need to copy `numbers.xml` from English. Maybe the sync tool should account for filling empty folders like that - it's so close to working, and another translator actually did the same thing earlier.

That said, have fun translating! :)

**Comment by sporksmith** [comment]
@Daaaav thanks! Yeah initially I'd only read the [programmer's README](https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/lang/README-programmers.txt), incorrectly expecting some programming to be involved for adding a whole new language. When I read about the sync tool I thought huh, maybe that'll work, and indeed it *mostly* did :)

Later I saw the instructions to copy the `en` folder in the [translator's README](https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/lang/README-translators.txt). Maybe it'd be worth duping those instructions in the programmer's README...

I'll probably just start over doing it the recommended way.
