### ISSUE TITLE
gitmodules and release version

### ISSUE THREAD

**Issue by pirate486743186** [TerryCavanagh/VVVVVV#1111]
The modules work in the release version? It is missing .git and the command doesn't seam to work. I tried doing a git pull but nothing seamed to happen.

I'm not a programmer, either it's broken( you removed .git) either you left out something from the instructions.

**Comment by InfoTeddy** [comment]
Yes, the zip and tarball don't include submodules. You will have to either:

1. Download each dependency manually.
2. Clone the repository instead. If you want to be sure it's the release version, do `git checkout 2.4`.

**Comment by Daaaav** [comment]
The "Releases" on Github aren't the place to get the game - the zip and tarball added to the release are just automatically added by Github whenever a release is tagged, and apparently aren't complete enough by themselves, so it's better to clone it via git if you'd like to compile the game for yourself.

Or you can also get VVVVVV via its official distribution platforms like [Steam](https://store.steampowered.com/app/70300/VVVVVV/), [itch.io](https://terrycavanagh.itch.io/vvvvvv), etc. If you need a free version, there's also the [Make and Play](https://thelettervsixtim.es/makeandplay/) edition.

**Comment by i0ntempest** [comment]
Would be great if the releases actually contain a complete tarball. GitHub Workflow can automatically do that on every release if configured (like [this](https://github.com/pytorch/pytorch/commit/51a67d3168107b64923d6e9925b5223ac1e82ffc), we can just take this file with a few modifications and I'll be setup. I'll submit a PR, but this is my first time touching workflows so I'll need some time.

**Comment by InfoTeddy** [comment]
> Would be great if the releases actually contain a complete tarball. GitHub Workflow can automatically do that on every release if configured (like [this](https://github.com/pytorch/pytorch/commit/51a67d3168107b64923d6e9925b5223ac1e82ffc), we can just take this file with a few modifications and I'll be setup.

We can do that manually but that doesn't prevent GitHub from automatically including links named "Source code" which don't have the submodules.

**Comment by i0ntempest** [comment]
> We can do that manually but that doesn't prevent GitHub from automatically including links named "Source code" which don't have the submodules.

Doesn't matter though, a tarball from a workflow will be a separate file. Anyways the PR is up.

**Comment by InfoTeddy** [comment]
Either way the release process is the responsibility of @flibitijibibo so he gets to decide what should be done here.

**Comment by InfoTeddy** [comment]
> I think this will be a total mess when trying to debug. You are introducing dev versions of dependencies. You are also breaking the convention of dev/release version separation.

Okay, assuming for the sake of argument that this is true...

> I would recommend to drop the submodules and just directly copy an exact version that you hand picked. Wasn't this way earlier?

I don't see how this solves any of those concerns that you just brought up. Yes, this is what we did before we switched to submodules, but we were also using interim commits of dependencies.

Regarding dev/release version separation, that is a totally separate concern that has nothing to do with which method we choose to manage our dependencies.

**Comment by flibitijibibo** [comment]
The out-of-tree changes include a VS2010 fix and a memset, both of which are documented and intend to go upstream - we'll update the submodules when the patches are in, in which case we'll be in sync again, or we'll fork and update the URLs, again putting us back in sync.

If this was something like the kernel I'd agree, but this is a game with prebuilt binaries... I'm still going to make the cleaned up zip but I'm going to cut this short before I read something that changes my mind here.

**Comment by flibitijibibo** [comment]
VVVVVV-2.4.zip is now included in the release:

https://github.com/TerryCavanagh/VVVVVV/releases/tag/2.4
