### ISSUE TITLE
Add GameCube glyphs

### ISSUE THREAD

**Issue by flibitijibibo** [TerryCavanagh/VVVVVV#1116]
How on Earth did I forget this one...

Detection is easy since the adapter uses the Nintendo vendor and its own product ID, so I think it just comes down to assets. I can handle the code if anyone is willing to handle asset updates.

**Comment by Fussmatte** [comment]
I can draw up the glyphs real quick, I just need to know which buttons exactly need to be covered - there's a pretty common third-party GC pad for Nintendo Switch but its button layout differs a little bit, mainly with the shoulder buttons. Should I worry about that or just the official pads?

**Comment by flibitijibibo** [comment]
The official Nintendo layout should be okay, this is primarily targeting the 4-slot Wii U/Switch adapter.

**Comment by Fussmatte** [comment]
Hopefully these will suffice ("START" will likely better suffice as text just as the generic layout):

![VVVVVVbutton_12squared](https://github.com/TerryCavanagh/VVVVVV/assets/44736084/2db11f18-bff5-4b4a-9c4d-186ea5da8c9b)
![VVVVVVbutton_10squared](https://github.com/TerryCavanagh/VVVVVV/assets/44736084/fde9c3fb-5c44-49b1-8c16-d60df7b9c25a)
![VVVVVVbutton_8squared](https://github.com/TerryCavanagh/VVVVVV/assets/44736084/368ce16f-1b56-42c0-a36d-0e914171108f)
