### ISSUE TITLE
Backbuffer is always 32bpp

### ISSUE THREAD

**Issue by JayFoxRox** [TerryCavanagh/VVVVVV#112]
In this code, the `graphics.backBuffer` is created in 32bpp, but with the color masks from `gameScreen.GetFormat()` (which might be 16bpp for example if the `gamesScreen` has that format):

https://github.com/TerryCavanagh/VVVVVV/blob/f9525020bbcb4c2f5c44218cadcd475bcc1d2037/desktop_version/src/main.cpp#L124-L133

According to the SDL documentation, if this value is larger than 8, then the masks are used anyway. So I assume this is a bug?

Note that all other surfaces (like `foregroundBuffer`) use `fmt->BitsPerPixel` instead.

**Comment by flibitijibibo** [comment]
I most likely did that while making sure it was like the SDL 1.2 window surface, though I don’t have the exact changeset anymore. I probably used my own masks, then ended up copying the masks, though I would have copied the bit depth as well. Hard to say!
