### ISSUE TITLE
confusing releases

### ISSUE THREAD

**Issue by pirate486743186** [TerryCavanagh/VVVVVV#1123]
As it is now it's confusing. you have two source releases without the modules and a third one with the modules.... Maybe it's obvious for github afficionados, it's not so obvious for the rest of us.

Also it would be nice to have the version in the name of the extracted folder of the full source release. It can cause conflicts since all future releases extract in the same folder. This should be fixed in the next release.

**Comment by Daaaav** [comment]
Technically the two "wrong" packages can't be deleted I'm pretty sure.

But if you just upload the correct one enough, nobody can find them anymore...

![Assets](https://github.com/TerryCavanagh/VVVVVV/assets/44736680/bffa11bb-7a46-47a8-92d8-633faed616eb)

**Comment by InfoTeddy** [comment]
Won't fix because it's impossible to delete the two automatic "Source code" files from GitHub releases.
