### ISSUE TITLE
Support for Windows XP 32-bit apparently dropped

### ISSUE THREAD

**Issue by Daaaav** [TerryCavanagh/VVVVVV#1145]
This can probably be quickly closed as "not worth the effort to support OS versions _this_ dinosaur", but since the Windows version is apparently still compiled with VS2010, I don't immediately see what made it incompatible...

Source: a comment on https://terrycavanagh.itch.io/vvvvvv

![itch.io message](https://github.com/TerryCavanagh/VVVVVV/assets/44736680/5531f7ba-877b-4ae0-97f3-a29eea5b97e9)

(It's kind of an entitled remark, for an OS we're probably one of the last apps to even still have supported in the first place, and I don't think anyone would blame us for not supporting it anymore except for this person 😛)

**Comment by flibitijibibo** [comment]
It might be SDL that stopped working, I dunno... I know we recently patched SDL3 with fixes for XP, but I don't have a setup to test with. They're welcome to build from source to see what's wrong, I'd be okay with patching stuff in since there's hardly any OS stuff in the game anyway...

**Comment by flibitijibibo** [comment]
Ah, yeah you're right - if the relevant upstream commit doesn't fix this we should revive that ticket. (At the same time they should probably backport the fix to a stable release if it _does_ work...)

**Comment by Daaaav** [comment]
Seems like what recently got merged was a fix for a similar Windows 7/8 split, so XP is still not supported unless we explicitly set _WIN32_WINNT to signal XP as a minimum target version.

**Comment by Daaaav** [comment]
Just checked the 2.4.1 Steam build on XP and that also doesn't work.

I'm pretty sure it doesn't require any code patches - we just need to define `_WIN32_WINNT` to `0x0501` for PhysFS, to make it not use any Vista+ only APIs.

**Comment by flibitijibibo** [comment]
Need to rebuild the nonSteam packages anyhow, so I'll do that today. (Will skip Steam since they don't even support <10 anymore...)

**Comment by Daaaav** [comment]
Refrigerator approved!

![2.4.1 on XP](https://github.com/TerryCavanagh/VVVVVV/assets/44736680/82c17f16-5d09-47e8-b8e7-0b4e0752426f)
