### ISSUE TITLE
The back button on Android does not close the application

### ISSUE THREAD

**Issue by olekstomek** [TerryCavanagh/VVVVVV#1165]
With the game running, I click the "back" button in Android and see a toast with the information "press again to exit", I click again or even many times and nothing happens. The only option is to exit the application via the "home" button.
Fresh installs and same behavior on two different devices: Xiaomi Mi 9 with Android 11 and Samsung Galaxy A52 5G with Android 14.

**Comment by NyakoFox** [comment]
The android port isn't finished -- I already implemented this in #1164

**Comment by olekstomek** [comment]
Okay! I didn't see this PR previous. I'm closing this issue, it's clear.

**Comment by leo60228** [comment]
I assume this issue is about the Adobe AIR version currently on the Play Store, not about the SDL2-based port. In this case, I think it would still be valid, albeit unlikely to be fixed before the AIR version is replaced.
