### ISSUE TITLE
Corrupted sprite glitch

### ISSUE THREAD

**Issue by Buggem** [TerryCavanagh/VVVVVV#1215]
I'm not sure how this exactly happened, but it happened while I was messing around with custom level scripting.
Here is the level that causes the glitch and screenshot (just skip through the dialogue until it happens)
[Katmandu.zip](https://github.com/user-attachments/files/17963450/Katmandu.zip)
![Screenshot from 2024-11-30 10-08-23](https://github.com/user-attachments/assets/64b3f251-7dd9-41ad-b7e0-1e1df672b873)

**Comment by Buggem** [comment]
pac man

**Comment by NyakoFox** [comment]
You used a script which modifies the player's sprite. This isn't a glitch, and it's not "corrupted".

**Comment by Buggem** [comment]
@NyakoFox but it only does it when run twice (during the same script)

**Comment by Daaaav** [comment]
There's no bug to be fixed here - main game scripts weren't meant to be called at random points in custom player levels, so whatever goes wrong when things aren't in place how the scripts were expecting them is the level maker's loss.
