### ISSUE TITLE
Raspberry Pi Port Issue

### ISSUE THREAD

**Issue by 9a3eedi** [TerryCavanagh/VVVVVV#130]
First and foremost, thank you very much for releasing the VVVVVV source code!

I took the opportunity to see if I can build the program on a Raspberry Pi 3 running Raspbian, so that my nieces can play the game on their (educational!) computer. It's really just a quick try... I have OpenGL enabled with KMS. Amazingly, the source builds just fine. I got a copy of the data.zip file from Steam and placed it in the build directory and ran the game. 

The initial load screen appears, but then I end up with a black screen. At the moment, I don't have speakers connected, so I'm not sure if there's sound.

The following are the console messages.

```
Base directory: /home/pi/.local/share/VVVVVV/
Save directory: /home/pi/.local/share/VVVVVV/saves/
Level directory: /home/pi/.local/share/VVVVVV/levels/
libsteam_api.so not found!
		
		
		       VVVVVV
		
		
		  8888888888888888  
		88888888888888888888
		888888    8888    88
		888888    8888    88
		88888888888888888888
		88888888888888888888
		888888            88
		88888888        8888
		  8888888888888888  
		      88888888      
		  8888888888888888  
		88888888888888888888
		88888888888888888888
		88888888888888888888
		8888  88888888  8888
		8888  88888888  8888
		    888888888888    
		    8888    8888    
		  888888    888888  
		  888888    888888  
		  888888    888888  
		
		
Unable to open file mmmmmm.vvv
The complete reloaded file size: 61651755
data/music/0levelcomplete.ogg unpacked
data/music/1pushingonwards.ogg unpacked
data/music/2positiveforce.ogg unpacked
data/music/3potentialforanything.ogg unpacked
data/music/4passionforexploring.ogg unpacked
data/music/5intermission.ogg unpacked
data/music/6presentingvvvvvv.ogg unpacked
data/music/7gamecomplete.ogg unpacked
data/music/8predestinedfate.ogg unpacked
data/music/9positiveforcereversed.ogg unpacked
data/music/10popularpotpourri.ogg unpacked
data/music/11pipedream.ogg unpacked
data/music/12pressurecooker.ogg unpacked
data/music/13pacedenergy.ogg unpacked
data/music/14piercingthesky.ogg unpacked
data/music/predestinedfatefinallevel.ogg unpacked
Quick Save Not Found
Teleporter Save Not Found
```

Some interesting notes:

- libsteam_api.so is probably impossible to get on the raspberry pi, but I assume it ignores it.
- Not sure what mmmmmm.vvv is, but I'm assuming it's music and I can see it loading them as .ogg files from the zip file... unless I'm missing something?

Any hints on where to look next to fix would be appreciated.

**Comment by flibitijibibo** [comment]
Everything looks legit - at this point it comes down to SDL’s (“new”?) KMS video backend and the RPi’s GLES implementation (I know 4 has Mesa, not sure about 3). Can you try using SDL’s latest Hg revision?

https://hg.libsdl.org/SDL

Unfortunately the closest device I have locally is a Steam Link, so I won’t be too helpful... but I know it works on low-power devices, SDL’s GLES2 backend is okay, and we don’t have any CPU arch dependencies, so that hopefully narrows it down quite a bit.

**Comment by 9a3eedi** [comment]
I have cloned the latest SDL and latest SDL_mixer, built and installed, and used the newly built versions to build VVVVVV but I still get a black screen as before, unfortunately. 

Though, can the game run on GLES? I was under the impression that it requires OpenGL, so I enabled RPi's experimental GL driver. I do remember it not working with GLES though... I'll try again later with GLES and the newly built SDL libs

**Comment by 9names** [comment]
I recommend trying the RetroPie SDL2 branch. I had similar issues with upstream on the Rpi 1.
They have a script for automatically cloning the right branch, building, and installing.
https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl2.sh

**Comment by flibitijibibo** [comment]
Sounds like a device-specific issue - we support quite a few renderers (software, d3d9, d3d11, gl, gles, metal) so if none of them work, this is probably the device acting up. The SDL source also includes some basic tests like `testgles` so I would check that out to make sure the device is working like it should.

**Comment by InfoTeddy** [comment]
> Not sure what mmmmmm.vvv is, but I'm assuming it's music and I can see it loading them as .ogg files from the zip file... unless I'm missing something?

`mmmmmm.vvv` is just the name of the file you drop in if you've purchased MMMMMM (the metal remix of PPPPPP, the game's soundtrack) and want to use it as a soundtrack in-game. You don't have to worry about it, and normally the game will load the soundtrack (PPPPPP) from the `vvvvvvmusic.vvv` inside `data.zip` if `mmmmmm.vvv` is non-existent.
