### ISSUE TITLE
Feature Request: Screen rotation

### ISSUE THREAD

**Issue by shantigilbert** [TerryCavanagh/VVVVVV#131]
I compiled the desktop version for the Odroid Go Advance, it runs perfectly except for one small caveat, the Odroid go advance needs screen rotation to -90 (or 90 CCW), is there a possibility this could be added?

Thanks

**Comment by parkerlreed** [comment]
I assume you are running SDL2 in the framebuffer/kms context?

**Comment by shantigilbert** [comment]
@parkerlreed Yes, exactly :)

**Comment by flibitijibibo** [comment]
This is more than likely something that needs to be handled in either SDL or whatever the display server is for the device. SDL supports automated rotations for platforms that have it, so as long as the platform implementation sends that information back the game should handle it without any changes on the application side.

**Comment by shantigilbert** [comment]
oh well, thanks anyways :)

**Comment by shantigilbert** [comment]
Just in case anyone else is in the same boat as me (no display server, etc) or using the Odroid Go Advance, with some google-fu and trial and error I came up with this patch (tested on the odroid go advance, with EmuELEC):

```
--- a/desktop_version/src/Screen.cpp
+++ b/desktop_version/src/Screen.cpp
@@ -109,7 +109,7 @@
 		SDL_SetWindowFullscreen(m_window, 0);
 		if (x != -1 && y != -1)
 		{
-			SDL_SetWindowSize(m_window, resX, resY);
+			SDL_SetWindowSize(m_window, 320, 480);
 			SDL_SetWindowPosition(m_window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
 		}
 	}
@@ -122,7 +122,7 @@
 	}
 	else
 	{
-		SDL_RenderSetLogicalSize(m_renderer, 320, 240);
+		SDL_RenderSetLogicalSize(m_renderer, 320, 480);
 		SDL_RenderSetIntegerScale(m_renderer, (SDL_bool) (stretchMode == 2));
 	}
 	SDL_ShowWindow(m_window);
@@ -169,12 +169,16 @@
 		m_screen->pixels,
 		m_screen->pitch
 	);
-	SDL_RenderCopy(
-		m_renderer,
-		m_screenTexture,
-		isFiltered ? &filterSubrect : NULL,
-		NULL
-	);
+
+	static int W = 320;
+	static int H = 480;
+	static int n = -90;
+	SDL_Rect dstrect;
+	dstrect.x = (W - H) / 2 - 1;
+	dstrect.y = (H - W) / 2;
+	dstrect.w = H;
+	dstrect.h = W;
+	SDL_RenderCopyEx(m_renderer, m_screenTexture, isFiltered ? &filterSubrect : NULL, &dstrect, n, NULL, SDL_FLIP_NONE);
 	SDL_RenderPresent(m_renderer);
 	SDL_RenderClear(m_renderer);
 	SDL_FillRect(m_screen, NULL, 0x00000000);

```
