### ISSUE TITLE
[Question] Linux build requirements

### ISSUE THREAD

**Issue by benwiley4000** [TerryCavanagh/VVVVVV#14]
I don't really want to ask y'all to put in a bunch of extra labor to figure out Linux build requirements when I'm assuming you just used what shipped with CentOS 7, but it would be nice to know what the additional build requirements are for other systems like Ubuntu especially, which is the most common base environment folks would be using who would want to build on Linux. It's possible we could figure this out just by trying to install and following the error messages.. I'm opening this issue to be able to track what those requirements are and hopefully add them to the desktop readme.

**Comment by benwiley4000** [comment]
Also related is finding the build requirements for Windows using MinGW and for Mac from the command line. Something that could run cross-platform in CLion for example. Not necessarily essential, but would be nice for someone wanting to build a cross-platform mod that doesn't need a vastly different build configuration depending on the platform. Unless you think there are essential components on Windows that depend on the platform libraries from Visual C++.

**Comment by fuzxxl** [comment]
I got it to build and run on FreeBSD with some minor patches.  It should thus work on any modern Linux distribution.

**Comment by flibitijibibo** [comment]
Building should only require a C and C++ compiler, CMake, SDL2-devel and SDL2_mixer-devel. Which compiler/editor and which host isn't a hard requirement, but the dependencies incurred from those build tools is for the builder to burden (in particular, MinGW builds will have to fuss with libgcc and libstdc++, osxcross builds may have dependency issues based on the SDK and C++ runtime, and Linux builds should be built against a _very_ low glibc version). The build is highly unsophisticated and doesn't require too much thinking to get going, so it's mostly a matter of whether or not you have prior experience building C++ programs using SDL.

**Comment by InfoTeddy** [comment]
@flibitijibibo Exactly which C++ version does VVVVVV use?

**Comment by flibitijibibo** [comment]
@InfoTeddy "Old"

**Comment by InfoTeddy** [comment]
@flibitijibibo But how old is old?

**Comment by flibitijibibo** [comment]
You'd have to test with `-std=c++??`, we don't know for sure.

**Comment by benwiley4000** [comment]
@fuzxxl Could you be specific about which patches you made? :) Thanks

@flibitijibibo thanks for the info

**Comment by flibitijibibo** [comment]
Probably the same changes as this: https://github.com/TerryCavanagh/VVVVVV/pull/11

**Comment by fuzxxl** [comment]
@benwiley4000 @flibitijibibo Precisely.  I did them in a slightly different way, but it was basically the same stuff as #11.

**Comment by sikthehedgehog** [comment]
Built it using Ubuntu 18.04 64-bit and it "just works" (I had the SDL2 development libraries already installed), so may want to add Ubuntu to the README. Honestly it looks to be hard to screw up with major distros anyway.

Only nitpick, probably because this is a 64-bit build (and the existing binaries seem to be 32-bit):
```
[ 36%] Building CXX object CMakeFiles/vvvvvv.dir/src/BinaryBlob.cpp.o
/home/████████/VVVVVV-master/desktop_version/src/BinaryBlob.cpp: In member function ‘bool binaryBlob::unPackBinary(const char*)’:
/home/████████/VVVVVV-master/desktop_version/src/BinaryBlob.cpp:111:55: warning: format ‘%li’ expects argument of type ‘long int’, but argument 2 has type ‘PHYSFS_sint64 {aka long long int}’ [-Wformat=]
  printf("The complete reloaded file size: %li\n", size);                                                       ^
```
Game does work, however.

**Comment by flibitijibibo** [comment]
See #26 for that warning.

**Comment by benwiley4000** [comment]
Indeed for me the install was also pretty painless after all, and the game works!

What I did:

- Ubuntu 18.04
- `sudo apt install libsdl2-dev libsdl2-mixer-dev`
- Per the instructions in the readme:
```
mkdir flibitBuild
cd flibitBuild
cmake ..
```
- After this you have to run `make` to get the executable (I guess the instructions before that are just for getting the project ready to open in an IDE).
- Go grab the Linux binary from [here](http://distractionware.com/blog/category/vvvvvv-make-and-play/) and run `unzip vvvvvv-mp-11192019-bin` in some empty directory somewhere else so you don't vomit a bunch of files in your build directory. It's gonna be in `data/data.zip` once you unzip.
- Include the data.zip file in the same `flibitBuild/` directory with the build.
- Finally you can run `./vvvvvv.x86_64` and the game will launch

**Comment by jpotier** [comment]
Tried the build here, I get to a binary I can start, with the following discovered dependencies

- "cmake-3.15.5"
- "gnumake-4.2.1"
- "SDL2-2.0.10"
- "SDL2_mixer-2.0.4"
- "physfs-2.0.3"
- "tinyxml-2.6.2"

but it crashes at start:

```
$ ./vvvvvv.x86_64
Base directory: /home/x/.local/share/VVVVVV/
Save directory: /home/x/.local/share/VVVVVV/saves/
Level directory: /home/x/.local/share/VVVVVV/levels/
libsteam_api.so not found!


                       VVVVVV


                  8888888888888888
                88888888888888888888
                888888    8888    88
                888888    8888    88
                88888888888888888888
                88888888888888888888
                888888            88
                88888888        8888
                  8888888888888888
                      88888888
                  8888888888888888
                88888888888888888888
                88888888888888888888
                88888888888888888888
                8888  88888888  8888
                8888  88888888  8888
                    888888888888
                    8888    8888
                  888888    888888
                  888888    888888
                  888888    888888


Unable to open file mmmmmm.vvv
The complete reloaded file size: 61651755
data/music/0levelcomplete.ogg unpacked
data/music/1pushingonwards.ogg unpacked
data/music/2positiveforce.ogg unpacked
data/music/3potentialforanything.ogg unpacked
data/music/4passionforexploring.ogg unpacked
data/music/5intermission.ogg unpacked
data/music/6presentingvvvvvv.ogg unpacked
data/music/7gamecomplete.ogg unpacked
data/music/8predestinedfate.ogg unpacked
data/music/9positiveforcereversed.ogg unpacked
data/music/10popularpotpourri.ogg unpacked
data/music/11pipedream.ogg unpacked
data/music/12pressurecooker.ogg unpacked
data/music/13pacedenergy.ogg unpacked
data/music/14piercingthesky.ogg unpacked
data/music/predestinedfatefinallevel.ogg unpacked
Quick Save Not Found
Teleporter Save Not Found
free(): invalid pointer
Aborted (core dumped)
```

**Comment by benwiley4000** [comment]
@jpotier I have exactly the same output except for the invalid free. My versions are slightly different than yours but not sure that's the issue:
- cmake 3.16.2
- libsdl2-dev 2.0.8
- libsdl2-mixer-dev 2.0.2
- make 4.1

What version of gcc/g++ do you have? I don't know that you necessarily need to go this extreme but for unrelated reasons I am running a cmake version that I built from source using my system g++. I assume that's unnecessary for this purpose.

Also not sure if irrelevant but I didn't install physfs or tinyxml like you did. I double checked in synaptic and I don't have those packages installed.

**Comment by benwiley4000** [comment]
Actually I guess it's possible that your problems could maybe arise from having multiple versions of physfs sitting around since it's already included in the library sources I believe. I'd remove the libraries you don't need (use the apt purge command actually if you're on Debian or Ubuntu). The readme says the only dynamically linked (external) dependencies are SDL2 and SDL2 Mixer.

**Comment by jpotier** [comment]
I'm running with gcc 8.3.0. I see now that physfs and tinyxml's sources are included, still, just running `cmake .. && make` complains about not finding them (if I don't include the shared ones), I need to look into that.

Fiddling with the generated Makefile directly, I can call:
```
$ make physfs-static
[ 10%] Linking C static library libphysfs-static.a
[100%] Built target physfs-static
```
which seems to indicate that static builds of both physfs and tinyxml can be built. Now I need to understand why the headers are not found

**Comment by flibitijibibo** [comment]
Does changing <> to “” for physfs.h fix it...? I would expect our includes to take priority either way, but maybe not.

**Comment by jpotier** [comment]
Unfortunately, same error.

**Comment by flibitijibibo** [comment]
Sounds like a whole other issue then - as others have mentioned, PhysicsFS and TinyXML are statically bundled, so the build system has absolutely no reason not to find them.

**Comment by benwiley4000** [comment]
Sounds crazy but you might want to try building a different version of cmake and generating/building with that to make sure it isn't the issue?

**Comment by JayFoxRox** [comment]
Please provide more complete command lines and environment information. Build with `make VERBOSE=1` for example, so you can see which include folders are passed to the compiler.

Also I feel like this issue has gone off-topic. Each problem should get its own issue. So you might want to start a new issue (or look for an existing one) about the include folder issue.

---

Bacl to topic: The wiki is open to the public, so someone can create start an article about dependencies on each Linux distribution (or link package configurations). I'd advise against linking binaries due to security and forward compatibility concerns.

**Comment by dkudriavtsev** [comment]
here's a `shell.nix` for NixOS:

```nix
{ pkgs ? import <nixpkgs> {} }:
with pkgs; mkShell {
  name = "vvvvvv-shell";
  buildInputs = [
    gcc gnumake cmake cmakeCurses SDL2 SDL2_mixer ninja
  ];
}
```

**Comment by benwiley4000** [comment]
@jpotier it's also possible that when you rerun cmake it relies on cached files so doesn't pick up that you want to use the included version. I'd try deleting your build directory and restarting, without trying to pass any fancy arguments into cmake. You really just need to pass it the source directory and it will handle things from there, assuming SDL2 and SDL2 are installed on the system level (you can just install them from apt repositories or whatever, not sure if that's what you did). I'd like to know if that works for your time because if it does then we probably have a good set of instructions for helping folks run the game on their systems. If not maybe there are edge cases which need to be worked out.

**Comment by jpotier** [comment]
@flibitijibibo @benwiley4000 @JayFoxRox I'm a fairly certain the problem comes from some lack of understanding how the nix standard environment (stdenv) works for building cpp projects. I have, of course, tried the verbose mode and I noted that cmake passes the `-I` option correctly. Also, I won't comment more on this until I have something, I am currently asking my distribution's community for help.

@dkudriavtsev I am quite interested to know if you get different results. I am also building a package for NixOS (although distribution is going to be tricky, so my scope was to keep it private for now): I started with a small nix-shell environment, here's what I have for the time being:

```
{ pkgs ? import <nixpkgs> {} }:

let
  binData = builtins.fetchurl {
    url = "http://www.flibitijibibo.com/vvvvvv-mp-11192019-bin";
    sha256 = "0jpw8ap4w37slhzrjs0l6izs34rvnksgp86n0aff3y5l27hhfwwz";
  };
in pkgs.mkShell {
  enableParallelBuilding = true;
  nativeBuildInputs = with pkgs; [
    cmake
  ];
  buildInputs = with pkgs; [
    gnumake
    SDL2 SDL2_mixer
    # If you include the following, it builds, but crashes: physfs tinyxml
    unzip
  ];
  shellHook = ''
    rm -rf desktop_version/flibitBuild
    rm -rf desktop_version/tmp

    pushd desktop_version
    mkdir -p flibitBuild
    mkdir -p tmp
    pushd tmp
    unzip ${binData}
    popd
    cd flibitBuild
    cmake ..
    make -j
    cp -v ../tmp/data/data.zip .
  '';
}
```

**Comment by flibitijibibo** [comment]
It sounds like at this point the remaining build issues are for third-party packaging, so I think we're good here... #20 may be interesting to a few people here, otherwise I think both the CI and the latest README do a good enough job.
