### ISSUE TITLE
Add source code changes?

### ISSUE THREAD

**Issue by mariomadproductions** [TerryCavanagh/VVVVVV#150]
You may not still have these, but it'd be interesting to look at old revisions of the source code to see how the game changed throughout its development.

**Comment by flibitijibibo** [comment]
I think there's still a revision history, but it wasn't very useful - mostly empty commit messages and undocumented changes. Simon might still have the full log but I think that's about all we have left, so nothing really to see unfortunately.

**Comment by mariomadproductions** [comment]
So the source for those early builds with the coins (etc) doesn't exist anymore?

**Comment by InfoTeddy** [comment]
Coins are still in the game, they're just unused. Same thing goes for the 1x1 breakable blocks (although the check to make them only disappear if your velocity is non-zero has been commented out), flip tokens, and one-way tiles.

**Comment by mariomadproductions** [comment]
I was just using that as an example of an early "state" of the game.

**Comment by mariomadproductions** [comment]
> I think there's still a revision history, but it wasn't very useful - mostly empty commit messages and undocumented changes. Simon might still have the full log but I think that's about all we have left, so nothing really to see unfortunately.

Even if its not very well documented, I think it'd still be interesting to see how the game developed from the start (or at least early on) to the finish. Unless you are saying that there isn't really any revision history?

**Comment by InfoTeddy** [comment]
I already asked Ethan about this. He doesn't have the original SVN repo, because he only came on with 2.2. The original repo is probably on one of Terry's or Simon's hard drives, and contacting either of them about it has so far not been very successful.

**Comment by InfoTeddy** [comment]
Also, the 2.0 release build still exists as an example of an "early" state of the game, or at least an earlier one. You just have to opt in to it on Steam (under "Betas") to obtain it. Simon's 2.1 builds were deleted at some point, but some people still have some of them around (@Dav999-v for example). The most accurate revision history that I know of (albeit incomplete) is this [Viki article](https://vsix.dev/wiki/Version_history_of_VVVVVV).

**Comment by TerryCavanagh** [comment]
> 
> 
> > I think there's still a revision history, but it wasn't very useful - mostly empty commit messages and undocumented changes. Simon might still have the full log but I think that's about all we have left, so nothing really to see unfortunately.
> 
> Even if its not very well documented, I think it'd still be interesting to see how the game developed from the start (or at least early on) to the finish. Unless you are saying that the revision history is gone now/was never kept?

Unfortunately there are no notes like that from the start - I didn't use source control back then! Wish I had! Simon's SVN notes wouldn't start until the C++ port.

**Comment by mariomadproductions** [comment]
Ah I see. Thanks for the answer.
