### ISSUE TITLE
Gamepad broken after 45491a0

### ISSUE THREAD

**Issue by shantigilbert** [TerryCavanagh/VVVVVV#167]
For some reason my gamepad does not work after 45491a03f3ec7b736fda130c0b575f414a9b5a6a, I use the SDL-GameControllerDB and it worked fine before this commit.

before when I ran VVVVVV it said 

`Opened SDL_GameController ID #0, odroidgo2_joypad`

Now this text does not appear at all, if I compile a version prior to this commit it works perfectly fine again.

**Comment by flibitijibibo** [comment]
What happens if you put the SDL_Init call after FILESYSTEM_init?

**Comment by shantigilbert** [comment]
You mean move line 66-69 to line 47 ? on main.cpp? I can try that and report back in a few hours.
Thanks

**Comment by shantigilbert** [comment]
yeah, that fixed it

```
--- a/desktop_version/src/main.cpp
+++ b/desktop_version/src/main.cpp
@@ -46,13 +46,7 @@
 
 int main(int argc, char *argv[])
 {
-    SDL_Init(
-        SDL_INIT_VIDEO |
-        SDL_INIT_AUDIO |
-        SDL_INIT_JOYSTICK |
-        SDL_INIT_GAMECONTROLLER
-    );
-
+  
     char* baseDir = NULL;
     char* assetsPath = NULL;
 
@@ -73,6 +67,13 @@
     {
         return 1;
     }
+
+  SDL_Init(
+        SDL_INIT_VIDEO |
+        SDL_INIT_AUDIO |
+        SDL_INIT_JOYSTICK |
+        SDL_INIT_GAMECONTROLLER
+    );
 
     NETWORK_init();
 
```

**Comment by flibitijibibo** [comment]
https://github.com/TerryCavanagh/VVVVVV/commit/0531ee9b197ee8c71954c7c903d9d6c2310ec6b9
