### ISSUE TITLE
[Enhancement] High-PPI icon

### ISSUE THREAD

**Issue by SirYodaJedi** [TerryCavanagh/VVVVVV#18]
[As discussed on the Steam forums](https://steamcommunity.com/app/70300/discussions/0/522730702208491999/#c37470847909454364), the icon (at least for the Windows executable) only goes up to 64x64. I cannot verify this; as I only have the 3DS version atm; but there should preferably be 96x96, 128x128, and 256x256 icons across Windows and Linux (and maybe 512x512 on OS X). Creating these icon sizes should be trivial, as the art style permits a integer upscale of the lower-resolution icons.

**Comment by flibitijibibo** [comment]
I forget why I used the icon that’s in data.zip, but we do indeed have super hi-res icons available to use. If I ever do another update I’ll look at updating data.zip.

**Comment by leo60228** [comment]
I'm not sure why macOS would have larger icons. People on Windows and Linux have HiDPI monitors too. If it's because of the icon size, I'm pretty sure that's configurable on all OSes. On my Linux system, I don't really notice a difference between icon sizes on the host and in a macOS VM.

**Comment by flibitijibibo** [comment]
The hi-res icon would end up being shared, so it’d apply to other high-DPI scenarios as well.

**Comment by SirYodaJedi** [comment]
> I'm not sure why macOS would have larger icons. People on Windows and Linux have HiDPI monitors too. If it's because of the icon size, I'm pretty sure that's configurable on all OSes.
I didn't mean to imply that OS X would get larger icons, but rather that it might actually benefit it. Windows won't display icons at sizes larger than 256x256 (it'll downscale them to that size). Linux is distro-dependent of course.

**Comment by flibitijibibo** [comment]
Apparently I did this a really long time ago and forgot about it - this is in the 2.3 release candidate!
