### ISSUE TITLE
SDL_BlitSurface is broken on raspberry pi

### ISSUE THREAD

**Issue by SoniEx2** [TerryCavanagh/VVVVVV#187]
I tried writing my own replacement but idk what it's supposed to do. otoh I got backgrounds and tiles to render, if with the wrong colors...

but uh, about sprites...

![IMG_20200322_112102](https://user-images.githubusercontent.com/1779619/77251812-4976b300-6c2f-11ea-919a-1442b6ccf040.jpg)

**Comment by flibitijibibo** [comment]
The surface blitters are all done in software so it should be the same everywhere. It sounds like the SDL revision may have the bad NEON optimizations enabled?

https://bugzilla.libsdl.org/show_bug.cgi?id=4365

If this is a stock SDL 2.0.12 binary, file a report on the Bugzilla.

**Comment by SoniEx2** [comment]
yep, it's trying (and failing) to use NEON optimizations.

I think I'm supposed to report this to raspbian maintainers somehow.

**Comment by flibitijibibo** [comment]
It should be disabled by default, so if they packaged it with that autoconf flag turned on that should definitely be reported to the Raspbian maintainers.

**Comment by flibitijibibo** [comment]
Closing this as "not our bug," but I would definitely complain about this if it's still present in the 64-bit beta distro that's in development right now.
