### ISSUE TITLE
Repository description could be more thorough

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#196]
Currently, as it is, "The source code to VVVVVV!" doesn't mean anything to anyone not familiar with VVVVVV. Why even have a description at all if you're going to re-print the name and nothing else?

Instead, it could do well to at least somewhat describe the game. Maybe something like "A retro game about reversing your gravity".

**Comment by flibitijibibo** [comment]
Only Terry can modify the header so I’ll defer to him, but perhaps we can just add a URL to that section, probably to http://thelettervsixtim.es/.

**Comment by TerryCavanagh** [comment]
Sure, done.
