### ISSUE TITLE
[Third Party] Package it as a Flatpak and get it on Athenaeum

### ISSUE THREAD

**Issue by DontUseGithub** [TerryCavanagh/VVVVVV#2]
- https://github.com/flathub/flathub/wiki/App-Submission
- https://gitlab.com/librebob/athenaeum

**Comment by flibitijibibo** [comment]
It should be possible to automate building the latest tip of this repo against the freedesktop SDK (which should include SDL2/SDL2_mixer), grabbing the MakeAndPlay data.zip, and uploading to a Flatpak repo, but be sure to define `MAKEANDPLAY` and mark it as a community build if you actually do this!

**Comment by ananace** [comment]
Should be no problems with setting the MakeAndPlay data as an extra-data source for the Flatpak either, then it can be uploaded to repos without containing any data at all - only a link to where the data zip can be automatically downloaded and extracted from.
The same feature is used by the [Spotify Flatpak](https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L165-L174) - among other - to avoid hosting potentially licensed content.

**Comment by flibitijibibo** [comment]
Going to close this in favor of #20, since they're pretty much the same and there's a nice checklist over there!
