### ISSUE TITLE
In webpage, md5sum hash of linux's file does not match

### ISSUE THREAD

**Issue by madacol** [TerryCavanagh/VVVVVV#207]
In the webpage https://thelettervsixtim.es/makeandplay/ the downloaded file at https://thelettervsixtim.es/makeandplay/vvvvvv-mp-11192019-bin has the hash `fdb083f5495c31a95229decde31168ef` instead of the publicized `d8f8bc84c660fd22d039d0adbeea728f`

**Comment by TerryCavanagh** [comment]
Oh, huh, I really feel like I've fixed this one before. That's kinda weird.

Uh, @flibitijibibo, is there any way for you to confirm that the file that's actually on my server, https://thelettervsixtim.es/makeandplay/vvvvvv-mp-11192019-bin, is legitimate?

**Comment by flibitijibibo** [comment]
I can't seem to find the exact file in my archives, but I do remember this coming up before - the files I have on my site do match if we want to do a quick reupload before 2.3 to be safe, but I don't recall what the change might have been to cause an md5 change.

**Comment by flibitijibibo** [comment]
Pulled down the file on the server and it seems to just be a mess of bytes... so if someone tried to make something malicious, they didn't do a very good job!

The flibit URLs are still valid and the md5s check out, so it probably just needs to be reuploaded.

**Comment by TerryCavanagh** [comment]
Reuploaded! Thanks @flibitijibibo 🎉 

Yep, not sure exactly what happened here, but I recently did a lot of work to fix up my server so I suspect it's something to do with that - maybe a random corrupted upload. This should be fixed now, though (I also reuploaded windows and mac for good measure).
