### ISSUE TITLE
How to compile mobile version

### ISSUE THREAD

**Issue by imaandrew** [TerryCavanagh/VVVVVV#221]
I would like to compile the mobile version of VVVVVV but I don't know how to start. I noticed in the folder that it requires Adobe AIR but that's all the guidance it gives. How do you compile the mobile version?

**Comment by InfoTeddy** [comment]
I haven't personally tried compiling the mobile version myself, but some quick internet searches tell me that you'll need to download [the Adobe AIR SDK](https://www.adobe.com/devnet/air/air-sdk-download.html) to compile it, apparently.

**Comment by TerryCavanagh** [comment]
Ah, yep - I'll add some better instructions soon.

You basically want to download flashdevelop, create a blank air mobile project, and copy the source into that. You'll also need to hook up all the audio packages (basically "inlining" classes that contain compressed audio in a special adobe format that's a licensed version of MP3).

It is possible to just compile it with the air sdk on a commandline, but I've never done that and I don't know what's involved.

**Comment by ThatWeirdAndrew** [comment]
So I've been trying to compile this and I've been getting lots of undefined property errors about GameCenter. I assume this is because I don't have the Game Center extension from Milkman Games installed. Is there any way to get around this? I've tried deleting the file scoreclass.as and removing references to it but there are lots of lines using the property scores.

**Comment by InfoTeddy** [comment]
Instead of deleting it, why not just make it a dummy class? That way you won't have to change all references to it.

**Comment by TerryCavanagh** [comment]
Try this one instead!

[githubrequireszips.zip](https://github.com/TerryCavanagh/VVVVVV/files/4572468/githubrequireszips.zip)

**Comment by ThatWeirdAndrew** [comment]
I still get lots of errors about a possibly undefined method through a reference with static type scoreclass.

**Comment by TerryCavanagh** [comment]
Ah - ok, you can just comment out any line that refers to Scoreclass - it should work.

**Comment by ThatWeirdAndrew** [comment]
After commenting out all of the lines referencing scores, I was able to compile the swf file. I had to set _JAVA_OPTIONS to -Xmx1g but I was able to finally compile an apk that ran fine on my phone. Thanks for your help!

**Comment by ThatWeirdAndrew** [comment]
Adobe AIR didn't show up in the play store for me so I had to download it [here](https://airdownload.adobe.com/air/android/download/25.0.0.134/AdobeAIRAndroid.apk)

**Comment by leo60228** [comment]
For what it's worth, VVVVVV-CE has Android support for the C++ version. If you want to build it, you could look at the CI files for guidance (note that GitHub Actions has the Android SDK preinstalled).

**Comment by TerryCavanagh** [comment]
Oh, I'm sorry, this one fell off my radar completely.

I'm not sure how much interest there is in this these days, but I compile this with FlashDevelop using the following .as3proj file and batch files to call commands from the android sdk:

[VVVVVV mobile build files.zip](https://github.com/TerryCavanagh/VVVVVV/files/10143130/VVVVVV.mobile.build.files.zip)

The latest version on Android is built with Harman Air SDK 50.0, which you can get from here: https://airsdk.harman.com/
