### ISSUE TITLE
Holding down left-click in the editor no longer works

### ISSUE THREAD

**Issue by AllyTally** [TerryCavanagh/VVVVVV#25]
For some reason, I can't hold down left-click in the editor to place tiles with the tile tool, they're only placed on the first frame the button is held. Holding down right-click works, though!

**Comment by flibitijibibo** [comment]
This is going to sound really odd, but this a debug build, right? (For Windows, is /RTC still on?)

Seems fine for me locally, but it's pretty easy to trace around if you want to check it out on your setup: https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/src/KeyPoll.cpp#L119

**Comment by AllyTally** [comment]
I'm pretty sure I've been compiling debug builds, that seems to be the default in Visual Studio 2017.

**Comment by flibitijibibo** [comment]
Someone in the speedrunning Discord made an interesting guess... does undoing this change fix it?

https://github.com/TerryCavanagh/VVVVVV/commit/146cdde217175b4ac0a37d7058ebe8b70bb6dc48

**Comment by AllyTally** [comment]
I tried that earlier but it didn't change anything.

**Comment by flibitijibibo** [comment]
Okay, phew, that would have been particularly cursed if that worked.

Unfortunately I don't think it's the game itself; `leftbutton` is only set to 1 when we get a button down event and is only set to 0 when we get a button up event, at no other point is leftbutton modified. So I suppose you could trace the mouse button events and see if it's the OS...? Or the hardware(!)?

**Comment by AllyTally** [comment]
Alright, thanks for your help

**Comment by AllyTally** [comment]
As far as I can tell, leftbutton seems fine.

**Comment by flibitijibibo** [comment]
Oh, weird! Yeah, I would see where delay gets set, I'm sure there's a gap in the massive tree somewhere.

**Comment by AllyTally** [comment]
I'm gonna close this because I'm most likely compiling it wrong since it works fine on Linux lol

**Comment by InfoTeddy** [comment]
I'm pretty sure that an oversight leading to undefined behavior was the cause of this bug. See #173.
