### ISSUE TITLE
[Editor] Mouse coordinates not scaled to viewport

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#27]
It seems like if you're in stretch mode, the game will still keep tracking your mouse position as if the window was still 320x240. So if your window is (say) 640x480, then the mouse position is more accurate near 0,0 but gets slowly more out-of-sync with the in-game cursor the more to the right and bottom you move it.

I recommend trying this on a build without 146cdde217175b4ac0a37d7058ebe8b70bb6dc48 so you can clearly see the mouse cursor.

**Comment by flibitijibibo** [comment]
That's definitely us not scaling the mouse for the viewport. A proper fix would be to translate window coordinates to screen coordinates.
