### ISSUE TITLE
Problems with custom assets

### ISSUE THREAD

**Issue by AllyTally** [TerryCavanagh/VVVVVV#271]
I've noticed a few issues with #262, #268 and #269.

- The custom assets loading only cares about graphics, and not about sounds or music (verified by looking through the initial pull requests commits).
- Assets (well, the graphics) don't get unmounted when you leave the editor, meaning they persist on the main menu and into the main game.
- When assets get unmounted when you return from the main game, the menu music doesn't play.

[Here's a video showcasing all of the issues.](https://o.lol-sa.me/7bG2oUZ.mp4) For context, when I start playtesting in my level, it's supposed to play a custom sound, instead of the vanilla sound.

**Comment by leo60228** [comment]
The first issue was caused by @Fussmatte forgetting to merge 1b7761d6658d4b36cd9ccaf115eeb49733efa3b2. This is currently a pretty large memory leak, I'll open a PR.

**Comment by leo60228** [comment]
Well, merging 1b7761d6658d4b36cd9ccaf115eeb49733efa3b2 will fix the bug, but it won't fix the memory leak. That also needs e533c69513e01039f9f2b876d934fe2b7a327055, which is more complex. As far as I can tell, all other VCE commits touching that code are only necessary for the `playfile` command added by VCE.

**Comment by InfoTeddy** [comment]
This should still be kept open, #273 only said:

> Partially fixes #271

GitHub's auto-issue-closer still flagged that sentence as a request to close this issue.

**Comment by flibitijibibo** [comment]
Checking on this real quick - how much of this is still present in the current revision?

**Comment by InfoTeddy** [comment]
Only the first bug listed is fixed. Later today I'll try to fix the other two.
