### ISSUE TITLE
Cmake unable to locate SDL_mixer.h

### ISSUE THREAD

**Issue by MAO3J1m0Op** [TerryCavanagh/VVVVVV#290]
I'm trying to build VVVVVV on macOS catalina. I should preface this with the fact my knowledge of C++ is mediocre and I don't know how cmake works. When running `cmake`, I get the following output:

```
CMake Warning at CMakeLists.txt:33 (MESSAGE):
  CMAKE_OSX_SYSROOT not set and macOS 10.9 SDK not found! Using default one.


-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using macOS SDK at /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
-- Using TARGET SDL2::SDL2
-- Configuring done
-- Generating done
-- Build files have been written to: /Applications/VVVVVV (2.3-pre)/desktop_version/build
```

However, once I try running `make`, the program fails with the below error:

```
In file included from /Applications/VVVVVV (2.3-pre)/desktop_version/src/Entity.cpp:3:
In file included from /Applications/VVVVVV (2.3-pre)/desktop_version/src/Map.h:13:
In file included from /Applications/VVVVVV (2.3-pre)/desktop_version/src/Music.h:4:
/Applications/VVVVVV (2.3-pre)/desktop_version/src/SoundSystem.h:4:10: fatal error: 'SDL_mixer.h'
      file not found
#include <SDL_mixer.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/VVVVVV.dir/src/Entity.cpp.o] Error 1
make[1]: *** [CMakeFiles/VVVVVV.dir/all] Error 2
make: *** [all] Error 2
```

From snooping around in the generated `depend.make` files, I can tell that SDL2 was found properly, but not the mixer. My mixer is installed at `/usr/local/Cellar/sdl2_mixer/2.0.4/include/SDL2/SDL_mixer.h`, but clearly the cmake script is not finding it. What can be done to fix this issue?

**Comment by MAO3J1m0Op** [comment]
After posting this, I realized that I duplicated Issue #41.

**Comment by flibitijibibo** [comment]
The expectation is that the SDL_mixer header is in the same folder as the SDL headers - as far as I'm concerned this is a Homebrew bug. A temporary fix would be to `mkdir /usr/local/include/SDL2` and copy the headers from SDL and SDL_mixer into that folder, after which the build should work (provided Homebrew didn't screw up the libraries as well).

**Comment by MAO3J1m0Op** [comment]
I placed a copy of `SDL_mixer.h` in `/usr/local/Cellar/sdl2/2.0.12_1/include/SDL2` (where Homebrew put SDL2), and the code compiled.
