### ISSUE TITLE
Refactor the gigantic state machine

### ISSUE THREAD

**Issue by multun** [TerryCavanagh/VVVVVV#297]
I just wanted to share the fact the C++ type system is expressive enough to implement pretty amazing stuff with state machines!

You can make [a framework](https://github.com/multun/libauto/) that:

 - has independent states in their own separate header
 - can check at compile time if a transition between state is valid (the check can be pretty much anything as long as it only depends on the source and destination states)
 - has per-state persistent variables
 - dispatches events to each state using virtual methods
 - logs all transitions if configured to
 - does not allocate memory dynamically
 - makes your compilation time skyrocket, which can get the project RealWorld C++™ certified

I understand anybody volunteering to rework this is very unlikely, but I figured sharing this stuff wouldn't harm!

**Comment by flibitijibibo** [comment]
If someone writes it and it works with the required compilers, works for me... but it’s not a fix (or even a feature, really), so it’s not something that will go on the TODO, it would only be considered once it’s in patch form.

**Comment by InfoTeddy** [comment]
As long as all `gamestate()` commands in custom levels still work (i.e. the state numbers are all kept the same) I don't see why not.

You could try your hand at refactoring the Super Gravitron state machine as a starting point, I'm pretty sure that won't break any custom levels or anything.

**Comment by TerryCavanagh** [comment]
This isn't planned, and I don't really see the point of it. I worry that leaving this issue open would encourage people to waste time on this pointless task. Closing.
