### ISSUE TITLE
[Docs] Crash when data.zip is missing

### ISSUE THREAD

**Issue by rcampbel3** [TerryCavanagh/VVVVVV#3]
Hi! Thanks for opensourcing this. I pulled the code down on ubuntu 19.10 did the following:

git clone
cd VVVVVVV/desktop_version
mkdir build
cd build
cmake ..
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No TARGET SDL2::SDL2, or SDL2, using variables
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ross/project/VVVVVV/desktop_version/build

make
(completes successfully

cd build
./vvvvvv.x86_64
Base directory: /home/ross/.local/share/VVVVVV/
Save directory: /home/ross/.local/share/VVVVVV/saves/
Level directory: /home/ross/.local/share/VVVVVV/levels/
libsteam_api.so not found!
		
		
		       VVVVVV
		
		
		  8888888888888888  
		88888888888888888888
		888888    8888    88
		888888    8888    88
		88888888888888888888
		88888888888888888888
		888888            88
		88888888        8888
		  8888888888888888  
		      88888888      
		  8888888888888888  
		88888888888888888888
		88888888888888888888
		88888888888888888888
		8888  88888888  8888
		8888  88888888  8888
		    888888888888    
		    8888    8888    
		  888888    888888  
		  888888    888888  
		  888888    888888  
		
		
double free or corruption (out)
Aborted (core dumped)

**Comment by flibitijibibo** [comment]
libsteam_api.so is optional, but data.zip is not. You will need to download it via a purchased copy or from the Make and Play Edition.

**Comment by TerryCavanagh** [comment]
You can find the data.zip file you need here!

http://distractionware.com/blog/category/vvvvvv-make-and-play/

Gonna update the build instructions to include this step, since it seems to be causing some confusion!

**Comment by flibitijibibo** [comment]
@rcampbel3 @JayFoxRox README has been updated, does this clarify things?

https://github.com/TerryCavanagh/VVVVVV/tree/master/desktop_version#including-datazip

**Comment by JayFoxRox** [comment]
Yes, although it's not clear to me as to why the mobile version gets it for free, but the desktop version doesn't.

**Comment by FredrIQ** [comment]
One thing that was unclear to me was that the data.zip must be included in the same directory you use to run the binary, using the standard compilation instructions. I figured this out after watching why it crashed in gdb (it was having trouble with the lack of sound files, and it was clearly looking for it relatively to the run directory).

**Comment by flibitijibibo** [comment]
@JayFoxRox The Flash docs should probably note that the Flash data.zip has the same restrictions, will let Terry get that one...

@FredrIQ Added the data.zip location to the docs!

**Comment by TerryCavanagh** [comment]
The flash docs mention that the flash data file is under the same restrictions as the c++ one! I think it's pretty clear as is, but happy to make changes...

**Comment by rcampbel3** [comment]
Thanks for the quick response. It works!

Could you host just the data.zip file for download on your page and include the link to it in the url or have the CMakefile download it at build time? Right now, you have to download the make and play edition for Linux, make download executable, run executable and install it, and then copy the data.zip file into VVVVVV/desktop_version/build and then go back and clean up the stuff I don't need.

also, could you add an install rules to cmakefile? :) Thanks!

**Comment by flibitijibibo** [comment]
@rcampbel3 It probably would be easier to have data.zip somewhere... but FWIW, on Linux you can `unzip` the installer and it'll dump everything to data/.

Definitely no to the install target though, we would need to implement mounting from XDG root system folders (i.e. `/usr/share/`) first before even considering that, and even then it would only be useful for third-party builds anyway.

**Comment by CCF100** [comment]
@TerryCavanagh Not sure the best way of contacting you, but it looks like the links on that blog post are down...

**Comment by benwiley4000** [comment]
@flibitijibibo I was pretty confused up until the point where you said you can `unzip` the binary. That helped me out a bunch! Now the game's working for me. :)

**Comment by flibitijibibo** [comment]
At this point I believe this is resolved... if we host data.zip as its own file I'll update this thread, but for now we've bulletproofed it enough I think.
