### ISSUE TITLE
Error compiling editor.cpp

### ISSUE THREAD

**Issue by acd2001** [TerryCavanagh/VVVVVV#300]
With gcc810 in windows (MinGW), editor.cpp  goes wrong:

[ 97%] Building CXX object CMakeFiles/VVVVVV.dir/src/editor.cpp.obj
c:/VVVVVV-master/desktop_version/src/editor.cpp: In function
 'std::__cxx11::string find_tag(const string&, const string&, const string&)':
c:/VVVVVV-master/desktop_version/src/editor.cpp:180:39
: error: expected ')' before 'SCNx32'
             sscanf(number.c_str(), "%" SCNx32, &character);
                   ~                   ^~~~~~~
                                       )
c:/VVVVVV-master/desktop_version/src/editor.cpp:184:39
: error: expected ')' before 'SCNu32'
             sscanf(number.c_str(), "%" SCNu32, &character);
                   ~                   ^~~~~~~
                                       )
make[2]: *** [CMakeFiles/VVVVVV.dir/src/editor.cpp.obj] Error 1
make[1]: *** [CMakeFiles/VVVVVV.dir/all] Error 2
make: *** [all] Error 2

**Comment by InfoTeddy** [comment]
Paging @leo60228, he's the one who added these lines. But after some quick internet searches, it seems like a `#define __STDC_FORMAT_MACROS` is needed?

**Comment by leo60228** [comment]
That should fix the problem. Note that that macro may or may not be required on C99 and is never required for C11. I'm guessing MinGW's glibc is older than mine? Anyway, I can make a PR in an hour or two.

**Comment by leo60228** [comment]
For some reason, MinGW requires `_POSIX_SOURCE` to be defined for these macros to be present if compiling C++99. I don't see a clear reason for this behavior, and there isn't anything backing it up standards-wise.
