### ISSUE TITLE
PhysicsFS library version

### ISSUE THREAD

**Issue by ePirat** [TerryCavanagh/VVVVVV#31]
Does the PhysicsFS library sources in the repo correspond to a specific upstream version (if yes, which?) or does it has custom changes on top?

**Comment by flibitijibibo** [comment]
PhysFS is vanilla 3.0.2! Not the easiest way to check, but:

https://github.com/TerryCavanagh/VVVVVV/blob/master/desktop_version/physfs/physfs.h#L434

**Comment by flibitijibibo** [comment]
Think I answered this - for completion's sake, I'll point out that if Ryan used Git instead of Hg we'd probably have this as a submodule :P

**Comment by ePirat** [comment]
Yep, thanks.

**Comment by Moth-Tolias** [comment]
@flibitijibibo does this mean that this repo will / could use submodules in the future?

**Comment by flibitijibibo** [comment]
I doubt it, the dependencies are really small and updates are mostly `cp * folder/`.
