### ISSUE TITLE
Disable VSync option for Haiku

### ISSUE THREAD

**Issue by win8linux** [TerryCavanagh/VVVVVV#345]
The game builds on Haiku, but crashes soon after launching it.
This is the output in the terminal while attempting to run the game execuatable:

```sh
~/vvvvvv/desktop_version/flibitBuild> ./VVVVVV
Base directory: /boot/home/config/settings/VVVVVV/
Save directory: /boot/home/config/settings/VVVVVV/saves/
Level directory: /boot/home/config/settings/VVVVVV/levels/
gamecontrollerdb.txt not found!
Unlocking BLocker with sem 2175627 from wrong thread 98232, current holder 98234 (see issue #6400).
GalliumContext: CreateScreen: Using llvmpipe (LLVM 7.0, 128 bits) driver.
                
                
                       VVVVVV
                
                
                  8888888888888888  
                88888888888888888888
                888888    8888    88
                888888    8888    88
                88888888888888888888
                88888888888888888888
                888888            88
                88888888        8888
                  8888888888888888  
                      88888888      
                  8888888888888888  
                88888888888888888888
                88888888888888888888
                88888888888888888888
                8888  88888888  8888
                8888  88888888  8888
                    888888888888    
                    8888    8888    
                  888888    888888  
                  888888    888888  
                  888888    888888  
                
                
Quick Save Not Found
Teleporter Save Not Found
Unable to open file mmmmmm.vvv
The complete reloaded file size: 61651755
data/music/0levelcomplete.ogg unpacked
data/music/1pushingonwards.ogg unpacked
data/music/2positiveforce.ogg unpacked
data/music/3potentialforanything.ogg unpacked
data/music/4passionforexploring.ogg unpacked
data/music/5intermission.ogg unpacked
data/music/6presentingvvvvvv.ogg unpacked
data/music/7gamecomplete.ogg unpacked
data/music/8predestinedfate.ogg unpacked
data/music/9positiveforcereversed.ogg unpacked
data/music/10popularpotpourri.ogg unpacked
data/music/11pipedream.ogg unpacked
data/music/12pressurecooker.ogg unpacked
data/music/13pacedenergy.ogg unpacked
data/music/14piercingthesky.ogg unpacked
data/music/predestinedfatefinallevel.ogg unpacked
no renderer found! 
Kill Thread
```

**Comment by flibitijibibo** [comment]
"No renderer found" is the part you'll want to check out.

**Comment by flibitijibibo** [comment]
Reasonably sure that this is caused by renderer recreation. I've tried to consolidate the bug to this one function in Screen...

https://github.com/TerryCavanagh/VVVVVV/commit/0f450f3e396c1a9f4e710211532ccfba4b1ac21c

... but the real fix is to stop messing with Screen when loading the config file. That said, the VSync option will probably still break on Haiku if it can't recreate the SDL_Renderer* at runtime.

**Comment by win8linux** [comment]
Trying now after the [commit](https://github.com/TerryCavanagh/VVVVVV/commit/0f450f3e396c1a9f4e710211532ccfba4b1ac21c) moving the VSync work to `Screen` and it does now run. However, attempting to turn it on crashes the program and requires reinstallation to work again. Despite this, the game does run without it enabled so I'm closing this issue as solved. 

Enabling VSync causing crashes on Haiku should prolly be in a different issue altogether.

**Comment by flibitijibibo** [comment]
I'd be up for disabling the in Haiku builds for 2.3 - the "real" bug is here:

https://bugzilla.libsdl.org/show_bug.cgi?id=5123

**Comment by win8linux** [comment]
Oh thanks, that would indeed be very much be appreciated! I will hold off on pushing a new update to the Haiku package until then.

**Comment by flibitijibibo** [comment]
Reopening so we don't forget to add the ifdef...

**Comment by flibitijibibo** [comment]
Option's now disabled for Haiku: https://github.com/TerryCavanagh/VVVVVV/commit/f8bb8cde326141cb410a9a219002f026e3941896

I still want to fix the config load timing to do the Screen init after it's loaded, but this at least makes it so it won't crash unless you go out of your way to do so.

**Comment by Begasus** [comment]
Still crashes on 32bit Haiku, probably not related but still ...
https://github.com/haikuports/haikuports/pull/5181#issuecomment-657240878
