### ISSUE TITLE
Coins no longer render

### ISSUE THREAD

**Issue by AllyTally** [TerryCavanagh/VVVVVV#347]
Coins spawned with `createentity(x,y,8,id)` no longer render. You can still collect them, and they function fine, but they just don't get rendered. [Here's a video of this, comparing 2.3 and 2.2.](https://o.lol-sa.me/9Thmk9G.mp4)

**Comment by flibitijibibo** [comment]
Do we have a bisect for this?

**Comment by flibitijibibo** [comment]
Scrolling through the commits, this is the only notable change to `createentity` specifically:

https://github.com/TerryCavanagh/VVVVVV/commit/de2d6a1e8683cac2c31191f3af2c34a3af1e3e62

Does reverting this commit fix the issue?

**Comment by AllyTally** [comment]
Currently doing `git bisect`, and the issue persists even before that commit.

**Comment by flibitijibibo** [comment]
Do you have a sample level that can be used to test?

**Comment by AllyTally** [comment]
The first commit that has broken coins seems to be 3699adec82786a58fed21e8381b0682af4f7b2c7. [Here's my VVVVVV prototype recreation, it's what I've been using to test this.](https://1drv.ms/u/s!Atgr4Erlbr68x1FSO42KiJrqiA8C?e=PwK1j4). It's called "VVVVVVVV" in the player levels list.

**Comment by flibitijibibo** [comment]
This fixes it for me:

```
diff --git a/desktop_version/src/Graphics.cpp b/desktop_version/src/Graphics.cpp
index c81d437..055271c 100644
--- a/desktop_version/src/Graphics.cpp
+++ b/desktop_version/src/Graphics.cpp
@@ -1754,7 +1754,7 @@ void Graphics::drawentities()
             FillRect(backBuffer, prect, obj.entities[i].realcol);
             break;
         case 4:    // Small pickups
-            setcol(obj.entities[i].realcol);
+            huetilesetcol(obj.entities[i].colour);
             drawhuetile(xp, yp - yoff, obj.entities[i].tile);
             break;
         case 5:    //Horizontal Line
```

@InfoTeddy, thoughts?

**Comment by InfoTeddy** [comment]
That makes the color of the entity update more than once per timestep (one 30 FPS frame). The original point of the commit was to prevent the colors from updating too fast. I'll debug it and see what I can figure out.
