### ISSUE TITLE
Some hotkeys still conflict with taking input

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#366]
- [ ] Using Alt+F to toggle fullscreen while input is being taken types F.
- [ ] Typing N or M during text input of `ed.getlin()` and level metadata editing will toggle the music and game mutes.

**Comment by InfoTeddy** [comment]
It's worth nothing that the second one seems to be a *regression* from 2.0 and 2.2 (those versions didn't have that issue).

**Comment by NicholeMattera** [comment]
Was taking a look at this and it looks like the music and game mute are working correctly. Typing m or n in a text input field doesn't seem to be muting the music/game. (Seems to be handled correctly by main.cpp:620)

I was however able to reproduce the Alt+F typing F in 2.2 and in the latest code, which I have a fix for.

**Comment by InfoTeddy** [comment]
> Typing m or n in a text input field doesn't seem to be muting the music/game. (Seems to be handled correctly by main.cpp:620)

Try this simple test: go to the editor, place down a checkpoint, press Enter. You should hear the checkpoint sound. Then press E to start editing the room name, type in "m", and then exit. Then press Enter again. The checkpoint sound should be gone now, meaning the game is muted.

**Comment by NicholeMattera** [comment]
That helps! I was changing the name of the level and it wasn't happening there. :+1:
