### ISSUE TITLE
Finding SDL automatically?

### ISSUE THREAD

**Issue by abdul** [TerryCavanagh/VVVVVV#38]
It would be nice to have SDL includes and libs found automatically, and used in the project. I found an interesting project that can be used here.

https://github.com/aminosbh/sdl2-image-sample

Thank you

**Comment by flibitijibibo** [comment]
This is already done without that file as far as I know. If this is on Windows I don’t know if that file actually helps.

**Comment by adrian17** [comment]
On Linux, CMake handles it out of the box. No idea how it works on Windows though.

**Comment by flibitijibibo** [comment]
Looking at the repo, the files are just the stock FindSDL2.cmake files, straight from the official project. Essentially, this is what Linux and macOS already do, and doesn't help Windows at all. Windows is pretty much destined to always be really bad at making development libraries easy to use. Good an excuse as any to treat Windows as a secondary target and use Linux instead!

It's not the answer we wanted, but unfortunately that's about as good as it'll get.
