### ISSUE TITLE
Segfault when saves/unlock.vvv doesn't exist and game attempts to create one

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#381]
The game segfaults whenever you specify your own base directory.

A quick look under GDB reveals that it segfaults on the line `SDL_GetWindowSize()` in `Screen::GetWindowSize()` in `Screen.cpp`. And if I print what `m_window` is, GDB complains that it cannot access the memory at address 0x10. Wait, what?!

Hmm, it doesn't print a pointer out, rather this actually says that the pointer itself is somehow stored at 0x10 for whatever reason.

Well, if I print `graphics->screenbuffer`, it says 0x0, which is NULL. And that's why 0x10 makes sense, because the pointer is at an offset of 0x10 from the start of the `Screen` object. So for some reason the `Screen` isn't getting initialized if we use `-basedir`.

**Comment by InfoTeddy** [comment]
Ok so the backtrace says this happens when `Game::savestats()` is called from `Game::loadstats()`, which only happens whenever there's no `saves/unlock.vvv` file. Which makes sense, people working on the code here usually already have an existing VVVVVV folder in place, but they have to use `-basedir` to change the directory around to another directory, and that directory is not guaranteed to have an already existing VVVVVV setup.

**Comment by InfoTeddy** [comment]
@flibitijibibo You were the one who changed the `Screen` init flow around, could you fix this?

**Comment by flibitijibibo** [comment]
I can take care of it later today if someone doesn't get it first - we can just fall back to default values if the window isn't present yet.

**Comment by flibitijibibo** [comment]
Pretty sure this takes care of it? https://github.com/TerryCavanagh/VVVVVV/commit/11312976fcb1ef9fe7e91791ab509e67c2004124

**Comment by InfoTeddy** [comment]
Yep, that seems to fix it!
