### ISSUE TITLE
You can get the "Er, how did you do that?" message on the Game Over screen in No Death Mode by rescuing the last crewmate and dying

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#383]
On the Game Over screen that happens whenever you die in No Death Mode, there is a short phrase that is printed at the bottom, determined based on the number of crewmates you have rescued.

If it's just 1 crewmate (yourself), it's "Keep trying! You'll get there!"
2 crewmates: "Nice one!"
3: "Wow! Congratulations!"
4: "Incredible!"
5: "Unbelievable! Well done!"

But if you rescue 6 crewmates, it says "Er, how did you do that?" This indicates that you're not intended to be able to have all 6 crewmates rescued at once when you die. After all, when you rescue the last crewmate, Viridian gets teleported to the Final Level and gets marked as missing, meaning you can only have at most 5 crewmates rescued at once.

Well, there *is* a way to have 6 crewmates and then die. You just have to rescue the last crewmate, but *don't* go through the teleporter. You'll know when the crewmate is counted as rescued when they make a happy squeak, turn happy, and start following you, and you can check with the CREW tab on the Enter screen to check.

Then you just die. It's always possible to die at the end of every zone without pressing R, because there are usually spikes there to enforce a one-way so you can't backtrack after grabbing the crewmate. However, the one-way is enforced in the Warp Zone by a warp token, and there are no spikes, so if you rescue Verdigris last, you'll have to press R.

**Comment by leo60228** [comment]
While I don't believe it was the intention, the message still makes sense. "Er, how did you [save all 6 crewmates without beating the game]?" vs. "Er, how did you [accidentally die right after getting a crewmate]?"

**Comment by flibitijibibo** [comment]
This should be a quick fix, just need one more string and we'll bump `case 6` to `default`, which should _actually_ be impossible to reach. @TerryCavanagh, any suggestions?

**Comment by TerryCavanagh** [comment]
I don't think this needs a change - the current string is an excellent reaction to somebody trying this, and was actually discovered by a speedrunner, who was delighted by it. It should stay as is.
