### ISSUE TITLE
Compiling errors with Graphics.cpp.o and Screen.cpp.o...

### ISSUE THREAD

**Issue by takenp** [TerryCavanagh/VVVVVV#39]
##Compiling under PuppyLinux (binary compatible with Ubuntu 14.04)

Sorry I'm not so experienced in compiling.. anyway.
cmake version 2.8.12/libSDL2 2.0.0

First I had to add to CMakeLists.txt to find SDL.h etc:

```
set(SDL2_INCLUDE_DIR /usr/include/SDL2)
set(SDL2_LIBRARY /usr/lib/libSDL2.so)
```

then I had to add c++ flag -std=c++0x to CMakeLists.txt

```
 CMAKE_CXX_FLAGS:STRING=-std=c++0x
```

for **Graphics.cpp.o** to avoid this "error: ‘nullptr’ was not declared in this scope"

then 
I got this issue for **Screen.cpp.o** :

>... In member function ‘void Screen::ResizeScreen(int, int)’:
>Screen.cpp:121:50: error: ‘SDL_RenderSetIntegerScale’ was not declared in this scope
>Screen.cpp:126:70: error: ‘SDL_RenderSetIntegerScale’ was not declared in this scope

..and stuck.

p.s.
BTW
if I run precompiled binary I'm getting this:

>./x86/vvvvvv.x86: undefined symbol: SDL_RenderSetIntegerScale

finish ;)

**Comment by takenp** [comment]
Is it because of the old version of SDL2?

**Comment by flibitijibibo** [comment]
Pretty much everything is too old, I think. The use of `nullptr` should be fixed though.

**Comment by flibitijibibo** [comment]
Fixed the nullptr issue: https://github.com/TerryCavanagh/VVVVVV/commit/ec070a11564187a6f29c34063749fd8ed0fe94a0

For everything else, the fix is unfortunately to upgrade your OS.
