### ISSUE TITLE
[Question] Do you accept constructive criticism?

### ISSUE THREAD

**Issue by kiroma** [TerryCavanagh/VVVVVV#4]

**Comment by TerryCavanagh** [comment]
Sure!

**Comment by oboforty** [comment]
Destructive criticism: buy Github pro and make this repo private, because no company will hire you

**Comment by flibitijibibo** [comment]
Bestructive criticism: "You should have more ASCII art in stdout"

**Comment by flibitijibibo** [comment]
I believe this has been answered - thanks for the question! If you do a writeup somewhere, link it to us here.
