### ISSUE TITLE
Allow music to be toggled on/off without muting the entire game.

### ISSUE THREAD

**Issue by tzann** [TerryCavanagh/VVVVVV#405]
If you want to play the game without the in-game music (e.g. when speedrunning) and want game sounds for the recording, but want to listen to no music (or different music), it's not possible.

**Comment by flibitijibibo** [comment]
This one's about as easy as it looks, we can add a key next to the mute key to only mute the Mix_Music track.

**Comment by tzann** [comment]
Either that or just add a menu option somewhere 🤷 either way, an easy QOL improvement :)

**Comment by InfoTeddy** [comment]
Uh... this already exists. It's the N key.

**Comment by tzann** [comment]
You are correct. I didn't see this change in the title of any pull request, my bad.

**Comment by tzann** [comment]
Apparently I'm just blind. It's in this one: https://github.com/TerryCavanagh/VVVVVV/pull/205
