### ISSUE TITLE
SDL_mixer.h header missing or not routed on MacOS Catalina

### ISSUE THREAD

**Issue by gcanosa** [TerryCavanagh/VVVVVV#41]
I just tried to compile VVVVVV on MacOS Catalina, and it was failing as follows:
[ 41%] Building CXX object CMakeFiles/VVVVVV.dir/editor.cpp.o
In file included from /Users/ethernet/tmp/VVVVVV/desktop_version/src/editor.cpp:5:
In file included from /Users/ethernet/tmp/VVVVVV/desktop_version/src/Music.h:4:
/Users/ethernet/tmp/VVVVVV/desktop_version/src/SoundSystem.h:4:10: fatal error: 'SDL_mixer.h' file not found
#include <SDL_mixer.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/VVVVVV.dir/editor.cpp.o] Error 1
make[1]: *** [CMakeFiles/VVVVVV.dir/all] Error 2
make: *** [all] Error 2

I've found the fix by copying SDL_mixer.h into "src" folder under desktop version.
So maybe path checks, or auto discover should be added into Makefile to get the real path of SDL_mixer.

**Comment by flibitijibibo** [comment]
This file should have gone into /usr/local/include/SDL2/ after installing from source.

**Comment by keithstellyes** [comment]
If it's installed from homebrew, it's installed to `SDL2/SDL_mixer.h` might be nice to have some sort  of detection, I've just been pre-pending `SDL2/` for now

**Comment by flibitijibibo** [comment]
The SDL2/ folder is accurate, but it should be in the same folder as the core includes, so that it’s found by `sdl2-config —cflags`. If they separate the satellite libraries and an extra path is required for mixer’s includes/libs, that’s a bug and should be reported to the packagers.

**Comment by ePirat** [comment]
I've checked and it seems homebrew packaged it correctly, the headers are in the expected location and sdl-config and pkg-config report the correct include paths, so that it should work fine.

**Comment by keithstellyes** [comment]
@ePirat didn't for me, did you have the SDL2 variables set? Might be why

**Comment by ePirat** [comment]
No, I do not. Can you provide your output of `sdl-config --cflags`?

**Comment by keithstellyes** [comment]
`sdl-config`: `-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE`

`sdl2-config`: `-I/usr/local/include/SDL2 -D_THREAD_SAFE`

**Comment by ePirat** [comment]
That looks right… And sorry I meant `sdl2-config` of course.
Apparently CMake does not use it for some reason? I've just tried to figure out but CMake logs nothing remotely useful even in the verbose logs it writes to the CMakeFile and build folder… What an amazing build system… I am out of ideas, sorry.

**Comment by flibitijibibo** [comment]
My guess is it's because Windows doesn't have it available - but it could still be used basically everywhere else, so I dunno. I think SDL's `./configure` also generates a file that doesn't use sdl2-config either, I forget if there's a reason for that.

**Comment by ePirat** [comment]
Do you mean the .pc file? Thats for pkg-config and is the defacto standard way (nowaydays these custom myprogram-config tools are rarely used) to find libraries for development on Linux (and macOS too, usually) by build systems (apparently not with CMake, it can fallback to it somehow apparently though, so maybe we should do that).

**Comment by flibitijibibo** [comment]
In addition to the pc file it's also possible to generate a CMake file:

https://hg.libsdl.org/SDL/file/e32309193634/sdl2-config.cmake.in

This is the template you'll see in Fedora's SDL2 CMake file, for example.

**Comment by ePirat** [comment]
Oh right I completely forgot CMake has kind of its own concept of .pc files… I suspect thats what it actually uses to find it on my system. But homebrew has that too so… it should just work?

@keithstellyes Can you share your `CMakeCache.txt` and a log of when you run CMake?

**Comment by keithstellyes** [comment]
`CMake Warning at CMakeLists.txt:18 (MESSAGE):
  CMAKE_OSX_SYSROOT not set and macOS 10.9 SDK not found! Using default one.


-- Using macOS SDK at
-- No TARGET SDL2::SDL2, or SDL2, using variables
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/keithstellyes/projects/ks/VVVVVV/desktop_version/build`

`CMakeCache.txt`: https://pastebin.com/raw/8N2gv7BR

**Comment by ePirat** [comment]
Thats not the full CMake configuration output, you need to run it in an empty build directory for the full output else CMake will use the cached values.

**Comment by ePirat** [comment]
Hmm it says:

```
//The directory containing a CMake configuration file for SDL2.
SDL2_DIR:PATH=/usr/local/lib/cmake/SDL2
```
so that looks right, like it should work… I have a similar entry in my CMake cache…

**Comment by flibitijibibo** [comment]
I think at this point it may have just been a one-user thing - we know installing from source works, and as the CI shows it works with brew as well:

https://github.com/TerryCavanagh/VVVVVV/blob/master/.github/workflows/ci.yml#L32

If the OP is still having build troubles, this can be bumped.
