### ISSUE TITLE
[Building] Array subscript error on Linux

### ISSUE THREAD

**Issue by rien333** [TerryCavanagh/VVVVVV#43]
So cool to see this source code available! 

However, I'm getting the following build error after running `make`:

```c
...
[98%] Building C object CMakeFiles/VVVVVV.dir/src/SteamNetwork.c.o
/tmp/makepkg/vvvvvv-git/src/VVVVVV/desktop_version/src/editor.cpp: In member function ‘voideditorclass::findstartpoint(Game&)’:
/tmp/makepkg/vvvvvv-git/src/VVVVVV/desktop_version/src/editor.cpp:1597:45: error: array subscript -1 is below array bounds of ‘edentities [3000]’ [-Werror=array-bounds]
 1597 |         game.edsavedir=1-edentity[testeditor].p1;
      |                          ~~~~~~~~~~~~~~~~~~~^
/tmp/makepkg/vvvvvv-git/src/VVVVVV/desktop_version/src/editor.cpp:2207:19: note: while referencing ‘edentity’
 2207 | extern edentities edentity[3000];
      |                   ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/VVVVVV.dir/build.make:89: CMakeFiles/VVVVVV.dir/src/editor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/VVVVVV.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
==> ERROR: A failure occurred in build().
```
Kinda unsure why it outputs `cc1plus: all warnings being treated as errors`, as the [cmake file](https://github.com/TerryCavanagh/VVVVVV/blob/a977f497250ba218e6c8b4722205df22348cc3fc/desktop_version/CMakeLists.txt#L8) should disable this.

## System details

- I'm using this [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vvvvvv-git#n42) (which pretty much just follows the build instructions for Linux)
- Build using
```console
$ uname -mor
5.4.10-arch1-1 x86_64 GNU/Linux
$ g++ --version
g++ (GCC) 9.2.0
$ cmake --version
cmake version 3.16.2
```

**Comment by flibitijibibo** [comment]
I would ask the PKGBUILD maintainer about this, AFAIK GCC should be fine with this (weird as it is).

**Comment by rien333** [comment]
They [directed me here](https://aur.archlinux.org/packages/vvvvvv-git/#comment-724331), as there is really nothing special about the PKGBUILD. 

However, when I manually perform the steps from the PKGBUILD, VVVVVV builds just fine. So this is probably indeed not a bug/issue, but an odd configuration problem on my side.

**Comment by JayFoxRox** [comment]
This is a valid error. Your system config probably enforces higher warning and error levels.

https://github.com/TerryCavanagh/VVVVVV/blob/901de4166e22d2795ead941de7d40a3e2444c2df/desktop_version/src/editor.cpp#L1589-L1598

This code will boil down to this:

```c
if(testeditor==-1) {
    game.edsavedir=1-edentity[testeditor].p1;
}
```

which is

```c
if(testeditor==-1) {
    game.edsavedir=1-edentity[-1].p1;
}
```

Which is indeed an out-of-bounds issue.

**Comment by rien333** [comment]
All right, I found the the offending piece of configuration. I'm building packages with `-O2` in my `CXXFLAGS` by default. Not sure if this a default from arch linux, but in general it's quite a reasonable flag. If I build without that flag enabled, the build doesn't error anymore. 

@flibitijibibo the code highlighted by @JayFoxRox  looks really fishy. So although building with `-O2` might not be supported,  it constitutes a (possible) bug that might lead to further (compilation) issues/warnings down the road.

**Comment by flibitijibibo** [comment]
Sounds like it’s worth investigating, if someone finds out what it does in reality and sends a patch I can merge it. For some reason I doubt that it’s as simple as changing it to a 0.
