### ISSUE TITLE
The Tower time trial fades out in the wrong place when ENTER is pressed

### ISSUE THREAD

**Issue by MAO3J1m0Op** [TerryCavanagh/VVVVVV#431]
While doing a time trial in the Tower, pressing ENTER (to restart the trial) shows the room "To the Batcave!" as the screen fades out. After that, the trial restarts like normal.

**Comment by InfoTeddy** [comment]
Duplicate of #367, same issue.

**Comment by flibitijibibo** [comment]
Closing as a duplicate, see #367 for more info.
