### ISSUE TITLE
macOS ARM Testing

### ISSUE THREAD

**Issue by flibitijibibo** [TerryCavanagh/VVVVVV#458]
Thanks to the latest osxcross work I can now do ARM64 Mac builds from flibitBuild. Only problem: I don't have the ARM hardware. I would like to have this for 2.3 if possible but that will only happen if someone with the transition kit can run the game and check it out. Thankfully there is no CPU-specific code in VVV and the build should be perfectly fine (minus an SDL patch that I just sent to the Bugzilla), but it'd be good to check on real hardware before sending it out.

**Comment by InfoTeddy** [comment]
What SDL patch?

And how would one get their hands on this hardware?

**Comment by flibitijibibo** [comment]
https://bugzilla.libsdl.org/show_bug.cgi?id=5259

You need to be a registered (read: paying) Apple developer, send in an application for the transition kit, and pay $500USD for it. So at minimum it's a $599 entry point assuming your application is accepted. I've never paid the subscription and don't intend to so I'm not eligible to apply.

**Comment by InfoTeddy** [comment]
Oh, right, I forgot, it's Apple and they really like taking money from people...

Well, it'd be nice if someone has the kit and is willing to test, but I doubt it's going to happen.

**Comment by leo60228** [comment]
It doesn't seem like testing this would be allowed under the Developer Transition Kit contract: https://developer.apple.com/terms/universal-app-quick-start-program/Developer-Universal-App-Quick-Start-Program.pdf

> You agree not to use the Developer Transition Kit for any purpose other than the testing and development by You (and Your Authorized Developers acting on Your behalf) of Your Applications or Your Internal Use Applications (hereinafter referred to collectively as “Applications”)

**Comment by InfoTeddy** [comment]
Damn... and I wager you can't simply pass the machine off to flibit as well. Thanks Apple.

**Comment by flibitijibibo** [comment]
Yeah, in this situation the only way this can be tested is to build and run from source, rather than use my binaries. But, if you have the DTK, you probably have the means to build VVV...

**Comment by leo60228** [comment]
My point is more that it's kinda unclear whether testing OSS code someone else wrote counts as "Your Applications."

**Comment by flibitijibibo** [comment]
That would pretty much disqualify all third-party programs and libraries of any kind; even so you could simply not redistribute the VVV binaries and call it "Internal Use" instead.

**Comment by flibitijibibo** [comment]
Has anyone given this a try now that the hardware is out? I won't be getting an M1 Mac myself so I still won't be able to test, but if it works I can just add the arch to the official builds...

**Comment by leo60228** [comment]
Could you upload M1 and/or DTK builds somewhere? I don't have either
myself, but I know several people with them.

**Comment by leo60228** [comment]
![image](https://user-images.githubusercontent.com/8355305/102830860-42482580-43b8-11eb-8219-b9cacbf7f8ef.png)

**Comment by flibitijibibo** [comment]
Cool, so whenever I get ARM builds in my routine this will come along with it. We don't have any CPU-specific work so as long as the dependencies are in order we're good to go.
