### ISSUE TITLE
Apply flip momentum to duplicate player entities

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#484]
The player gets a boost of momentum upon flipping, in addition to the gravity change. However, this is not applied to additional players created with `createentity(0,x,y)`. It's debatable whether this is a bug or a feature, but I believe it should be considered:
* The current behavior is, at the very least, unexpected
* #482 was merged, showing that improving support for duplicate player entities is, at the very least, not a *non*-goal
* I don't believe any levels currently released are making use of duplicate player entities
* Outside of contrived scenarios, I doubt this would prevent any new levels using duplicate player entities from being played in 2.2

**Comment by AllyTally** [comment]
> #482 was merged, showing that improving support for duplicate player entities is, at the very least, not a non-goal
That's fixing a regression.
