### ISSUE TITLE
[Proposal] Move third party folder to a subfolder

### ISSUE THREAD

**Issue by ePirat** [TerryCavanagh/VVVVVV#56]
Currently all third party libraries have their own folder in the top level of the repository alongside with `src`.

For better structure and clarity it might be a good idea to move them all into a subfolder called `third_party` or something, so it is clear this is not really part of VVVVVV and should not be touched (except when updating with upstream).

Additionally that would mean you can easily clarify that the license and copyright does not apply to all things in `third_party` instead of listing every single project, which would be especially useful if a project is added or removed there.

**Comment by flibitijibibo** [comment]
Good idea, done:

https://github.com/TerryCavanagh/VVVVVV/commit/894675c51288b47740b352b66c588a9d4265da95
