### ISSUE TITLE
[Editor] Original editor is missing

### ISSUE THREAD

**Issue by JayFoxRox** [TerryCavanagh/VVVVVV#6]
From http://distractionware.com/blog/2020/01/vvvvvv-is-now-open-source/:

> All the actual levels in the game are hardcoded in huge arrays that I generated with my own map editor, which exports the levels in source code that I could read in. This is just kind of how it worked when making a flash game in 2009 – accessing external data assets is hard to do, so it just made sense at the time to compile that into the game instead. All the really big files (like Spacestation2.cpp, Finalclass.cpp and so on) were made this way. I’ve uploaded the code for the editor [here](https://pastebin.com/9wqvBGuD) for completeness, but it’s not really useable anymore to be honest (it requires Allegro and Mingw to compile). I made a similar tool for rearranging the final level layouts!

Therefore, the content of https://pastebin.com/9wqvBGuD should be added to the repository to archive it and allow future changes. A CMake file should be created.

**Comment by TerryCavanagh** [comment]
Yep, you're right. I'm going to put this together later today and add it to the repo properly!

**Comment by TerryCavanagh** [comment]
Ok, it's added!
