### ISSUE TITLE
[Enhancement] Use the local storage folder for game data

### ISSUE THREAD

**Issue by parkerlreed** [TerryCavanagh/VVVVVV#60]
It seems in one of the more recent commits, data.zip being in the current working directory was forced. Earlier I was able to extract the assets to `~/.local/share/vvvvvv` (Yeah I know the folder is uppercase now)

Maybe in addition to $PWD, also include the `~/.local/share/VVVVVV` folder in the search?

**Comment by flibitijibibo** [comment]
The plan is to add support for XDG_DATA_DIRS, per #20. DATA_HOME is for user data, not static data.

**Comment by parkerlreed** [comment]
Thanks for the update. I'll keep an eye on that issue.
