### ISSUE TITLE
Physics regression with y-position after flipping off of horizontally-moving platforms and conveyors

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#606]
@anna328p on the VVVVVV Discord server reported being unable to do the Trench Warfare trick where you flip over the entire room in one flip. I was able to confirm her findings by creating a libTAS movie file that worked on 2.2 but desynced in 2.3.

The problem seems to be that when Viridian flips off of the horizontally-moving platform, their y-position is closer to the platform in 2.3 than in 2.2, and so they hit the wall and are unable to complete the flip in 2.3, while they completely miss it and complete the flip in 2.2.

2.2:
![Trench Warfare trick in 2.2](https://user-images.githubusercontent.com/59748578/106377116-87fcf400-634f-11eb-8282-480b1d31fdb3.png)

2.3:
![Trench Warfare trick in 2.3 (regression)](https://user-images.githubusercontent.com/59748578/106377115-87645d80-634f-11eb-94a5-8bd54f9f441b.png)

I heavily suspect this is caused by 942217f871bf1182ded3a915b8c26b90c04d561a (#509).

**Comment by InfoTeddy** [comment]
As suspected, reverting 942217f871bf1182ded3a915b8c26b90c04d561a fixes the bug. But that commit was made to fix being teleported to the y-position you had on the previous frame if you suddenly collided with a horizontally-moving platform or conveyor, which would fix a potential death loop if you had a checkpoint on a conveyor, since the savepoint height was made consistent for all checkpoints and custom level start points.

**Comment by flibitijibibo** [comment]
Sounds like it's something we should have in the speedrunner mode?

**Comment by InfoTeddy** [comment]
Not sure. I'm trying to understand the bug more thoroughly before making any decisions like that.

**Comment by InfoTeddy** [comment]
So after some investigation with libTAS and GDB, I see why the persistence of `newyp` here results in an additional 2 pixels when flipping off of the moving platform as soon as possible.

It's because their `newyp` was inside the moving platform, so the game applies the y-velocity of their ACTION press and sets their y-position (which is now floating off of the platform), before re-applying their y-velocity *again* on top of that same y-position after that.

# Explanation

To explain: the intended next y-position is still inside the moving platform on the second frame of Viridian being on the platform<sup>[note 1][note 2]</sup>.

So, on the next frame, Viridian flips off of the platform by pressing ACTION<sup>[note 3]</sup>. On that frame, when the horizontally-moving platform collision code gets ran in `gamelogic()`, it sees that Viridian is standing on the ceiling of the moving platform, then runs `entityclass::entitymapcollision()`.

Then, `entitymapcollision()` will see that their intended next y-position is inside the moving platform, and will react accordingly. It will recursively (1) decrement the magnitude of their y-velocity and (2) re-calculate their next intended y-position (by adding their current y-position plus the newly-assigned y-velocity), stopping only if their y-velocity ends up becoming 0 or if the re-calculated intended next y-position is no longer colliding with anything.

After that, it will then assign their y-position to the intended next y-position it just calculated.

So here, when `entitymapcollision()` gets called, it will re-calculate Viridian's intended next y-position while taking into account the y-velocity that just got set to 4 by pressing ACTION. This intended next y-position will end up no longer being in the moving platform, so the function returns, and that ends up being their y-position. However, this y-position ends up no longer being flush with the ceiling of the moving platform, and is basically floating off of it.

The kicker is that, after Viridian's intended next y-position got re-assigned by the platform logic calling `entitymapcollision()`, **Viridian is going to be updated again when the time comes to update all non-platform entities**. You see, `gamelogic()` has three separate entity loops, that get executed in order: one that updates vertically-moving platforms, one that updates horizontally-moving platforms, and one that updates the rest. The second loop has already called `entitymapcollision()` on the player, but the third loop is going to update them *again*.

So this time around, `updateentitylogic()` is going to calculate their intended next y-position, but *using the y-position that was already set in the second loop*, which is the one that's *already off of the moving platform*. So now they're farther from the moving platform than they already were previously. And this is why they have that "boost" in 2.2.

---

<sup>[note 1]</sup>: Due to frame ordering, you must be standing on a surface for at least 2 frames before you are able to flip off of it again.

<sup>[note 2]</sup>: The reason for their `newyp` still being inside the moving platform is that on the first frame of standing on the moving platform, when the collision code was recursively decrementing their y-velocity, the y-velocity went to 0 before their `newyp` got out of the moving platform.

<sup>[note 3]</sup>: Pressing ACTION does nothing but set `game.gravitycontrol`, their y-velocity, and their y-acceleration. Their position does not inherently change by pressing ACTION.

---

When #509 was merged, the `newyp` of Viridian before `entitymapcollision()` got called in the second loop ended up being the same as their y-position. Since this position is not inside the moving platform, they won't move an inch. So that's why 942217f871bf1182ded3a915b8c26b90c04d561a makes them flip off 2 pixels closer to the platform than before.

What I think we should do is to revert 942217f871bf1182ded3a915b8c26b90c04d561a, but re-fix the issue that that fix fixed in a different way (probably resetting the player's `newxp`/`newyp` in `mapclass::resetplayer()`). I'll submit a PR soon...

**Comment by TerryCavanagh** [comment]
This investigation has done a lot to quieten my worries about 2.3 potentially introducing new issues! Thank you for looking into this!
