### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by mithrendal** [TerryCavanagh/VVVVVV#608]
Hi @TerryCavanagh 

we adore your game and want to include the C64 demo version of VVVVVV on the showcases page for the web version of our VirtualC64 emulator on gh-pages.

please have a look here https://dirkwhoffmann.github.io/virtualc64/showcases.html
(click on the VVVVVV picture and the game starts)

since we are unsure about the license we like to ask you for your ok... 

we just put it to the page in the last hour ... the page is not yet linked from anywhere ... well except from here now 😎 ... if you are not ok with it we will remove it from the page immediately.

**Comment by TerryCavanagh** [comment]
Hey! This is totally fine with me! Good luck with it :)

I'm not sure where this falls, licence wise, since the C64 demo is something I authorised years ago, and is technically not related to the source release. You should probably check with Paul before you check with me, really! In any case, I've got no problem with this!

**Comment by mithrendal** [comment]
Hey @TerryCavanagh I am happy that you like it.😍 

For contacting Paul. I made extra an twitter account for this but I can't sent him any message, I guess he disabled it to get messages from any unknown twitter users.

How can I let him receive the question for the usage of his conversion ? Do you have an idea? Is he at github ?

**Comment by InfoTeddy** [comment]
You can still tweet at him; you don't necessarily have to send a DM.

**Comment by mithrendal** [comment]
Ah ok. Did not quite understand the concept behind twitter I guess 😬. I will try. Thanks anyway.
