### ISSUE TITLE
Uploading CI artifacts?

### ISSUE THREAD

**Issue by Cyuubi** [TerryCavanagh/VVVVVV#62]
Thought it would be cool if we had this, any reason why CI doesn't upload them?

**Comment by Cyuubi** [comment]
Bump?

**Comment by flibitijibibo** [comment]
We’re only using CI for basic build testing, official builds will be released only after proper testing is done for a specific revision. Non-developers should not be using builds from untagged Git revisions.

**Comment by InfoTeddy** [comment]
You can always fork the repo and edit the CI on your own. Just make sure to rebase when you pull from upstream or you'll end up with a lot of unnecessary merge commits.
