### ISSUE TITLE
data.zip missing in linked website

### ISSUE THREAD

**Issue by Vazgen7788** [TerryCavanagh/VVVVVV#65]

**Comment by TerryCavanagh** [comment]
Apologies, it'll be back up soon (i.e. next couple of hours)! (If you happen to have a commercial version of VVVVVV, you can grab the same zip files from there in the meantime!)

**Comment by TerryCavanagh** [comment]
Ok! This should be sorted out now. The new permanent URL for the Make and Play edition is https://thelettervsixtim.es/makeandplay/
