### ISSUE TITLE
Ubuntu 19.10: mesa brw_disk_cache error on run

### ISSUE THREAD

**Issue by thoughton** [TerryCavanagh/VVVVVV#68]
Built with reasonable ease (thanks!!) on Ubuntu 19.10, but when I try to run I get this error:
```
vvvvvv.x86_64: ../src/mesa/drivers/dri/i965/brw_disk_cache.c:405: brw_disk_cache_init: Assertion `note && build_id_length(note) == 20' failed.
Aborted (core dumped)
```
Any ideas on what it could be?  (Googling suggests it could be some kind of mesa shader cache error... maybe?!)

I have `data.zip` from the retail (Steam) version of the game copied next to my built executable.

(Note: I built using CMake's Ninja generator - could that be related?)

Thanks!

**Comment by flibitijibibo** [comment]
The assertion is in Mesa, so it's not us. Also it looks like your build is out of date, since the executable name has been modified recently.

**Comment by thoughton** [comment]
Ah yikes, sorry! I cloned on Friday and forgot to check if anything had changed since. Will update and try again - thanks!

**Comment by flibitijibibo** [comment]
Seems like this is a widespread issue and is indeed specific to Mesa, so I think we're good here...

**Comment by thoughton** [comment]
Hi @flibitijibibo - I've no problem with this being closed, but when you say it's "widespread" do you mean for VVVVVV, or in general?

Either way, if you came across any links I'd really appreciate it if you could share them, as I did a decent amount of searching but didn't find anything...

Thanks!

**Comment by flibitijibibo** [comment]
This is what I looked up:

https://www.google.com/search?client=firefox-b-1-d&q=brw_disk_cache_init%3A+Assertion+%60note+%26%26+build_id_length%28note%29+%3D%3D+20%27+failed.

**Comment by thoughton** [comment]
Brilliant, thank you. I appreciate it.

**Comment by thoughton** [comment]
Just in case anyone else encounters this, I've worked out a solution.

The solution was to ensure that pkg-config finds the _system-installed_ Mesa instead of the locally-built _latest_ version it was finding before.

Whether this indicates an actual bug in Mesa, an incompatibility with something else in my system, or a version mismatch with some other library I have no idea... But for now, I'm happy.

Thanks!
