### ISSUE TITLE
60 FPS mode should be the default in 2.3

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#702]
I've been playing through the game at 60 FPS, and I think it's great. I'd like to commit to it as the new default for the game!

I did a quick search in the code for `over30mode`, but just at a quick glance, it might be better if somebody more familiar with this made the change? I'm not that familiar with how the save system works anymore and I don't want to break anything.

**Comment by InfoTeddy** [comment]
It's probably as easy as initializing it to `true` in `Game::init()` - no point in switching the variable around to be negative, because booleans should generally be named in the positive (so the things we have like `graphics.notextoutline` is a bit... bad).

**Comment by TerryCavanagh** [comment]
Ok, good to know! I've made that change now.
