### ISSUE TITLE
Game lacks even basic audio options (aside from muting)

### ISSUE THREAD

**Issue by XenonZed** [TerryCavanagh/VVVVVV#706]
The game is quite loud compared to other applications on my computer and the only way to make it quieter is through the audio mixer. There really ought to be volume settings in the game itself. It's kind of absurd that these have never been implemented.

**Comment by InfoTeddy** [comment]
I will definitely add this in 2.4.

The only thing preventing it from getting in 2.3 is the fact that we are in a feature freeze currently (and are very close to release). @flibitijibibo, it's your call if this can be exempted from the feature freeze.

**Comment by flibitijibibo** [comment]
It shouldn't be too hard to add a float for music and sound that doesn't affect how the game works - just one more multiplier in the SetVolume calls. Still not _required_ for 2.3 but it'd be a pretty safe review if it got written.

**Comment by TerryCavanagh** [comment]
I hate to pile things onto 2.3, but this one is actually such an easy change, and it would be good to do it now while the menus are being reworked (I'll add an audio category and move the soundtrack option there too).

**Comment by InfoTeddy** [comment]
What a coincidence - I was just working on this too! I'll PR the audio controls in a bit and let you sort the menus out later.

**Comment by TerryCavanagh** [comment]
Ah, thank you! That sounds good to me, I haven't done any work on this yet 👍

**Comment by InfoTeddy** [comment]
Just kidding - I moved the audio options myself anyways:

#717

**Comment by TerryCavanagh** [comment]
haha, thanks @InfoTeddy!
