### ISSUE TITLE
C++ Standard

### ISSUE THREAD

**Issue by SuperV1234** [TerryCavanagh/VVVVVV#707]
Hello,

Any reason why the C++ Standard is explicitly set to C++98 in the `CMakeLists.txt` for the desktop version?
C++11 is ubiquitous, and C++14/17 are also very common nowadays.

Using a newer would make contributing to the source code easier and likely improve it in many places.

**Comment by InfoTeddy** [comment]
This has been brought up before, see the comments of ec070a11564187a6f29c34063749fd8ed0fe94a0.

Vee, I know where you're coming from, but it's really not worth it to bring this up again. It just leads to a heated debate. I'll let Ethan answer for why this game is still C++98, but other than that the conversation is most likely going to go nowhere.

**Comment by SuperV1234** [comment]
Note that the codebase already uses C++11-only features:

```cpp
In file included from C:\OHWorkspace\VVVVVV\desktop_version\src\BinaryBlob.cpp:3:
c:\ohworkspace\vvvvvv\third_party\physfs\physfs.h:316:23: warning: ISO C++ 1998 does not support 'long long' [-Wlong-long]
  316 | typedef unsigned long long    PHYSFS_uint64;
      |                       ^~~~
```

**Comment by InfoTeddy** [comment]
> Note that the codebase already uses C++11-only features

So, my intial reaction is "review the paths, please - that's PhysFS, that's not us" - however, I do wonder why including this header file works. I don't get the warning... maybe something to do with the difference between C89 and C++98?

**Comment by flibitijibibo** [comment]
Compatibility with VS2010 is still required for the official builds, and we have had others use the low std requirement for real use cases.

If we were to change the language in any way, it would be moving the codebase to C, so don't give me any funny ideas...

**Comment by SuperV1234** [comment]
> Compatibility with VS2010 is still required for the official builds

Why exactly VS2010?

**Comment by flibitijibibo** [comment]
2010 is what my Windows build setup uses for C++ builds - I've moved to MinGW for C builds but libstdc++ and its dependencies are a blocker, and I'm pretty careful about updating Visual Studio to a version Microsoft still touches, since at least for my type of work Microsoft not touching it is a feature and not a bug.

**Comment by InfoTeddy** [comment]
Poor wording on my part. It's mainly C89 but with some C99 extensions (such as `long long`).

**Comment by flibitijibibo** [comment]
Yeah, `long long` is really annoying in general - in C++ it's an '11 extension! I think SDL has (or had, I dunno anymore since even VS2010 has stdint.h) a bunch of weird stuff in the headers to get its 64-bit types.
