### ISSUE TITLE
Song fade-in (?) when loading save sounds glitchy

### ISSUE THREAD

**Issue by mcpower** [TerryCavanagh/VVVVVV#710]
Using the version on Steam (presumably based on f96f5703ff1798cb5e071ccadef43a8198261909) on Windows 10 20H2. See attached video, using Passion for Exploring.

https://user-images.githubusercontent.com/6015058/114289275-fc73b200-9ab9-11eb-8c21-6dd5a860902a.mp4

Pressure Cooker seems to be affected too, so it's not the single song:

https://user-images.githubusercontent.com/6015058/114289512-d818d500-9abb-11eb-88cd-a63a6e5d52bd.mp4

**Comment by InfoTeddy** [comment]
I think I know what you're talking about - there's 1 frame where the audio is at max volume. I've noticed it too.

The `settings.vvv` isn't needed (and it's actually `settings.vvv`, not `settings.xml`).

**Comment by mcpower** [comment]
Yep, that's exactly it.

I'll remove `settings.vvv` as it seems like it's not needed - thanks!

**Comment by flibitijibibo** [comment]
This can probably be addressed as part of #701, roughly affects the same place.

**Comment by flibitijibibo** [comment]
Thinking about this more, do we know if this is present in 2.2? It's still a blocker either way but if it's not a regression I can try to take care of this one.

**Comment by InfoTeddy** [comment]
I can confirm that this is not present in 2.2.
