### ISSUE TITLE
Selecting "return" in gameplay / graphics options returns to pause menu instead of options menu

### ISSUE THREAD

**Issue by mcpower** [TerryCavanagh/VVVVVV#711]
If you access the options menu via the pause screen, selecting "return" on the gameplay options or graphics options returns you back to the pause screen instead of returning to the options menu. Game pad options and accessibility options are not affected by this, and return back to the options menu instead of the pause menu.

https://user-images.githubusercontent.com/6015058/114289606-b10ed300-9abc-11eb-9eee-7e74f246ea94.mp4

**Comment by InfoTeddy** [comment]
Yeah, after Terry changed the options menus around it's a bit broken. I also noticed that returning from the "quit to menu" menu (whether by selecting no or by pressing Esc) puts you back at "options" too. This shouldn't be too hard to fix up...
