### ISSUE TITLE
Return to Play Menu from Time Trials Results doesn't function for me in 2.3

### ISSUE THREAD

**Issue by bcmccracken** [TerryCavanagh/VVVVVV#714]
I played Time Trials of the first level a few times, then quit from the Esc menu in the middle of one, which took me to the Results screen. From there, hitting Space/A on [ RETURN TO PLAY MENU] makes a sound and shifts the color of the screen but doesn't leave it.

I wish I'd captured more leading up to this, but here's at least footage of being stuck:

https://user-images.githubusercontent.com/31028880/114294833-06fc6000-9a56-11eb-87df-04251055cd5e.mp4

**Comment by InfoTeddy** [comment]
Looks like what happens is when you replay the time trial, the game pops off the last stack frame, but it seems like we're not actually adding any stack frames when we do the results screen? This will have to be investigated a bit more.

**Comment by TerryCavanagh** [comment]
Whoops, I thought I'd tested all the menus after the change, but I forgot this one. Should be an easy fix, I'll sort it out this week.

**Comment by InfoTeddy** [comment]
Nah, I don't think you caused this regression... pretty sure I did this one.
