### ISSUE TITLE
Quick Save option loads regular save instead

### ISSUE THREAD

**Issue by davmillar** [TerryCavanagh/VVVVVV#73]
I'm running v2.2 on 64-bit Fedora Linux.
**Steps to reproduce:**
1. Start game from terminal via shell script.
2. Play as normal.
3. Hit enter key to pull up map screen, arrow over to save option, and save game.
4. Hit escape key to exit, confirm decision to exit, reach title screen.
5. Choose to start game, choose to continue, arrow down to quick save, select it.

**Expected results:**
Continue from quick save point, e.g. ship room to the right of teleporter.

**Actual results:**
Continue from last teleporter save.

**Additional notes:**
On my initial play, the terminal output showed "Quick Save Not Found". After the first save, I tried exiting and re-launching and that line was no longer in the output.

Here's the permissions on the save folder:
```
$ ls -la /home/(redacted)/.local/share/VVVVVV/saves/
total 28
drwxr-xr-x. 2 (redacted) (redacted) 4096 Jan 13 18:35 .
drwxr-xr-x. 4 (redacted) (redacted) 4096 Jan 10 18:33 ..
-rw-r--r--. 1 (redacted) (redacted)  270 Jan 10 21:32 levelstats.vvv
-rw-r--r--. 1 (redacted) (redacted) 2635 Jan 10 21:21 linewrap.vvvvvv.vvv
-rw-r--r--. 1 (redacted) (redacted) 2356 Jan 13 19:12 qsave.vvv
-rw-r--r--. 1 (redacted) (redacted) 2347 Jan 13 19:28 tsave.vvv
-rw-r--r--. 1 (redacted) (redacted) 1290 Jan 13 19:28 unlock.vvv
```

Let me know if there are any additional logs or output needed to assist debugging.

**Comment by InfoTeddy** [comment]
Are you sure that you're not just confusing the teleporter save and the quicksave? The teleporter save is auto-saved every time you touch the teleporter, and if you quicksave after it'll be the same save. Can you upload both `qsave.vvv` and `tsave.vvv` for us?

**Comment by InfoTeddy** [comment]
Hold on, I re-read your issue just now...

> Continue from quick save point, e.g. ship room to the right of teleporter.

Quicksaves don't work that way. When you quicksave, you'll start at your last checkpoint. Teleporters count as checkpoints, too. So if you went to the ship's teleporter, and then moved to the right, and then quicksaved, you'll start at the ship's teleporter. This is intentional.

**Comment by davmillar** [comment]
> Quicksaves don't work that way. When you quicksave, you'll start at your last checkpoint. Teleporters count as checkpoints, too. So if you went to the ship's teleporter, and then moved to the right, and then quicksaved, you'll start at the ship's teleporter. This is intentional.

Oops. That makes perfect sense. I just tried it and it works exactly as described. Thank you for the explanation -- this is now a non-issue.
