### ISSUE TITLE
Warp Zone backgrounds' speed is framerate-dependent

### ISSUE THREAD

**Issue by liquidev** [TerryCavanagh/VVVVVV#735]
With the new 60 fps patch live, I noticed a fairly annoying bug in rendering of Warp Zone's backgrounds: their movement speed is dependent on the framerate of the game, which can be quite a bit distracting, especially in The Gravitron when your eyes try to focus on all the little squares flying towards you.

**Comment by InfoTeddy** [comment]
Are you sure about this? I made damn sure when writing the patch that nothing would be framerate-dependent.

**Comment by flibitijibibo** [comment]
This may need some recordings to verify - high framerates tend to make things look like they're going faster even though they end up being the same speed side-by-side.

**Comment by liquidev** [comment]
Ah, I just compared side by side and it seems that indeed the animation speed is fine. My 144 Hz monitor is probably making the movement look smeary, sorry for wasting your time on this!
