### ISSUE TITLE
When restarting a Time Trial with the Enter key, the music stops.

### ISSUE THREAD

**Issue by Fractodacto** [TerryCavanagh/VVVVVV#752]
Hello, I noticed a bug where the first time I play a time trial level, everything works fine. But then I die so I hit enter but the music stops playing but the sound effects are still there. I'm sorry I can't add like a video or anything.

**Comment by Fractodacto** [comment]
It seems to go away by going to the main menu

**Comment by InfoTeddy** [comment]
What is the date in the bottom-right on the title screen? If it's 2021-04-13, then you're on an older version of the build, and you're probably using the 2.3 beta; but it's not your fault, because Ethan hasn't updated the 2.3 beta. Regardless, I'm pretty sure this bug is already fixed.

**Comment by flibitijibibo** [comment]
I think this is fixed in the latest revision - if someone doesn't beat me to it I'll make a new build this weekend (office is currently down for repainting, of all things).

**Comment by InfoTeddy** [comment]
> if someone doesn't beat me to it

My [fork's CI branch](https://github.com/InfoTeddy/VVVVVV/actions?query=branch%3Aci) automatically uploads CI artifacts, but I only upload the default version (not the official version), which doesn't contain the Steam achievements. So I always have builds of the latest revision. Is it okay to use the default version for the beta? Seems like you'd want to disable achievements in the beta, anyways...

**Comment by Fractodacto** [comment]
Yeah I'm on the 2.3 beta, is there anyway to get updated to the newer versions for steam?

**Comment by InfoTeddy** [comment]
> is there anyway to get updated to the newer versions for steam?

As I have already explained, Ethan hasn't updated the 2.3 beta, so you'll just have to wait.

**Comment by Fractodacto** [comment]
Yup, that's fine with me!

**Comment by flibitijibibo** [comment]
Latest revision is now live on 2.3-testing.

**Comment by Fractodacto** [comment]
yup works great, thanks!
