### ISSUE TITLE
Implement touch controls in C++ version

### ISSUE THREAD

**Issue by leo60228** [TerryCavanagh/VVVVVV#759]
The idea here is pretty simple: forward-port the touch controls from Flash to C++. This would make future mobile ports much easier, and would benefit the WebAssembly port in #690 (which could be implemented as a [Progressive Web App](https://web.dev/progressive-web-apps/)). However, it could also be argued that this isn't worth the maintenance burden, since this wouldn't directly benefit any current ports.
[VVVVVV-CE had this](https://github.com/v6cord/VVVVVV-CE/commit/4ef8bac8738f4e66ab00dc24fa03b2d6c68c066b), though the implementation had little in common with the Flash release.

**Comment by flibitijibibo** [comment]
Once 2.4 has the action set system in place this will be _much_ easier to implement, so let's make this a part of that work - we probably won't use any of the code, but we can try and reimplement the UI where appropriate.

**Comment by TerryCavanagh** [comment]
I think it would be great to reproduce some of the VVVVVV mobile features in the desktop build, yep. There are actually quite a few nice things there between the little touch tutorial, the touch focused menus and all the different control options!

**Comment by InfoTeddy** [comment]
(Since this is required for 2.4, this isn't so much of an RFC (request for comments) anymore...)

**Comment by flibitijibibo** [comment]
Redirecting to...

- #834 for action sets
- #832 for the UI backport
