### ISSUE TITLE
Compiling on Windows: cannot find entry point for main

### ISSUE THREAD

**Issue by pratikone** [TerryCavanagh/VVVVVV#76]
I am using 64-bit Windows 10 with following CMAKE options : 
`cmake -G "Visual Studio 15 2017" .. -DSDL2_INCLUDE_DIRS="D:\github\vcpkg\installed\x64-windows\include\SDL2;" -DSDL2_LIBRARIES="D:\github\vcpkg\installed\x64-windows\lib\SDL2.lib;D:\github\vcpkg\installed\x64-windows\lib\SDL2_mixer.lib" -DCMAKE_GENERATOR_PLATFORM=x64` 

In trying to compile VVVVVV project within the solution, and the error gets thrown is : 
`LNK2019	unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	VVVVVV	D:\github\VVVVVV\desktop_version\build\MSVCRTD.lib(exe_winmain.obj)	1	`

Now, adding **main** as entry point in Visual Studio Linker options, adds more to the compilation problems. Apparently [SDL also defines a main which causes linker to complain](https://stackoverflow.com/questions/11976084/why-sdl-defines-main-macro).  Solution is doing `undef main` before VVVVVV's main. This results in more MSVCRTD related unresolved symbol errors.

Anyone had success in compiling on windows ?

**Comment by flibitijibibo** [comment]
You're missing SDL2main.lib in your SDL2_LIBRARIES definition.

**Comment by pratikone** [comment]
Thank you. That definitely solved it. Since I am using vcpkg (not entirely automated because that one doesn't link SDLmain either) for SDL. Here is my cmake command if anyone else wants to use it.
`cmake -G "Visual Studio 15 2017" .. -DSDL2_INCLUDE_DIRS="D:\github\vcpkg\installed\x64-windows\include\SDL2;" -DSDL2_LIBRARIES="D:\github\vcpkg\installed\x64-windows\lib\SDL2.lib;D:\github\vcpkg\installed\x64-windows\lib\manual-link\SDL2main.lib;D:\github\vcpkg\installed\x64-windows\lib\SDL2_mixer.lib" -DCMAKE_GENERATOR_PLATFORM=x64`
