### ISSUE TITLE
Game freezes momentarily when saving

### ISSUE THREAD

**Issue by KSSBrawl** [TerryCavanagh/VVVVVV#761]
Testing on both a binary compiled from source and the Steam 2.3 beta, whenever the game saves it freezes up momentarily like so:
https://user-images.githubusercontent.com/40847080/118382146-16704b00-b5b8-11eb-8da7-e2e08a8a3475.mp4

**Comment by InfoTeddy** [comment]
I've talked with @KSSBrawl and I would also like to clarify, this *is* a regression. They reported that it did not happen in 2.2.

I'm not sure what we can do; one of the causes of this freeze is that the game waits for the file to be written before continuing, i.e. the game blocks on file write.

**Comment by flibitijibibo** [comment]
I'm surprised a write so small is taking so long... anything special about the filesystem we should know about? We could hypothetically write to memory before writing to a file, but if the filesystem is going to block for that long there's not much we can do without spinning an entire thread, which is definitely overkill.

**Comment by flibitijibibo** [comment]
Checked and if anything, our new write should be faster - we write the XML to memory, then use PhysFS to write instead of TinyXML. The former uses the OS API directly, the latter uses stdio.

It might be worth timing the writeFile call to see if this is Windows (or whoever) getting in our way.

**Comment by KSSBrawl** [comment]
OS is Linux MInt 20.1, if that's any help.

**Comment by flibitijibibo** [comment]
I wasn't able to reproduce this locally - this is probably the line you want to time:

https://github.com/TerryCavanagh/VVVVVV/blob/master/third_party/physfs/physfs_platform_posix.c#L239

**Comment by InfoTeddy** [comment]
(This was closed because they were only able to reproduce it on only one specific machine of theirs.)
