### ISSUE TITLE
Gamepad mapping is somewhat unintuitive/buggy

### ISSUE THREAD

**Issue by nadiaholmquist** [TerryCavanagh/VVVVVV#784]
* Mapping in game actions such as flip or menu also overrides controls in the menu, this should ideally be mapped separately
* There is no (clear?) way to unmap a button from an action
* If a button is mapped to the "menu" action, it becomes impossible to remap this button to anything else
* Interact button can be mapped, but is not used unless the interact button is changed back to E in the speedrun settings, otherwise the enter button is used for interacting
* Interact button can't be used to advance dialog, this is of course consistent with playing on keyboard, though it feels somewhat weird on a controller

**Comment by InfoTeddy** [comment]
Yep, this is all just 2.4 stuff, and Ethan's territory I'm sure. Right now we're focusing on getting 2.3 out.

**Comment by flibitijibibo** [comment]
Yep, agreed that mappings are a mess - will try to eliminate all of these in the action set rewrite.

**Comment by nadiaholmquist** [comment]
Wow, fast response! Really looking forward to 2.3/2.4

Keep up the great work :)

**Comment by flibitijibibo** [comment]
Redirecting this issue to #834...
