### ISSUE TITLE
LICENSE.md incorrectly states that "All materials in the repo are copyright of Terry Cavanagh © 2010-2020."

### ISSUE THREAD

**Issue by FRex** [TerryCavanagh/VVVVVV#8]
The PhysFS and TinyXML are both zlib and (c) other people.

**Comment by flibitijibibo** [comment]
The licenses for both (as well as lodepng) are in their respective folders, but we probably should add a "with the exception of" part to the root license. I think we'll need the license author to make those modifications though, so this may take a while.

**Comment by FRex** [comment]
Lodepng too, yeah, for some reason I did a Lode == Terry in my head because I knew these two names before today.

Probably no one who uses zlib would go after someone over this, but they do have a "don't misrepresent" requirement so I mentioned just to let you go play safe, tight and by the book in the legal/license file itself.

**Comment by flibitijibibo** [comment]
I've adjusted the directory structure to make it easier to point out that third-party dependencies are not owned by Terry:

https://github.com/TerryCavanagh/VVVVVV/commit/894675c51288b47740b352b66c588a9d4265da95
