### ISSUE TITLE
Game segfault on startup

### ISSUE THREAD

**Issue by lithiumjs** [TerryCavanagh/VVVVVV#81]
Arch Linux 5.4.11 x86_64. Game compiles perfectly, but when I try to run it, it segfaults after outputting the crewmate ASCII-art. If I run it as root, it freezes, outputting `Unable to play WAV file: Tried to play a NULL chunk` every once in a while. I have no idea how to fix this, maybe you do?

**Comment by flibitijibibo** [comment]
Do not run the game as root.

Is this the latest master? It sounds like data.zip is missing, which the game should tell you in an error message.

**Comment by TijmenUU** [comment]
In my experience you're most likely not using the correct `data.zip` with it. Did you download the Linux version (make and play)? You could try the make and play one: unzip it (yes, you can unzip the `*.bin` file) and place it next to the compiled binary. Also make sure you're using a correct working directory, i.e. `cd` to where the binary (and now `data.zip`) lives and  run it, i.e. `./vvvvvv`.

**Comment by lithiumjs** [comment]
Ok, I fixed the issue. The problem was weird files in my ~/.local/share/VVVVVV/ folder (leftovers from some custom levels). It's working properly now.
