### ISSUE TITLE
How to run game (desktop version)

### ISSUE THREAD

**Issue by averagerikkafan** [TerryCavanagh/VVVVVV#812]
I compiled the desktop version, how to run the game?

**Comment by InfoTeddy** [comment]
Which platform are you on?

If it's Windows, `VVVVVV.exe` will be in either `Debug\` or `Release\`. You will need to download `data.zip` from [here](https://thelettervsixtim.es/makeandplay/) and place it in the same folder as `VVVVVV.exe`.

**Comment by InfoTeddy** [comment]
Assuming this is resolved, so I'm closing it.
