### ISSUE TITLE
Loading built-in level does not work

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#820]
If you try to load a built-in level (i.e. a level in `data.zip`), it will throw up an error that says nothing.

![Error with no message](https://user-images.githubusercontent.com/59748578/129137013-8beec6a6-348d-4f6d-8d2a-dea01d615327.png)

From the console output, it seems to be returning the path of the `data.zip` file whenever `PHYSFS_getRealDir()` is called on the level path in `FILESYSTEM_mountAssets()`.

```
Custom asset directory is .zip at /home/infoteddy/v/map/data.zip
Could not mount /home/infoteddy/v/map/data.zip: real directory doesn't exist
```

I've tried to do the bare minimum investigation as to why this happens, but haven't figured it out yet.

**Comment by flibitijibibo** [comment]
Kind of surprised because it usually does a good job of merging, but maybe load order has something to do with this.

**Comment by AllyTally** [comment]
This seems to happen without -assets, too.

**Comment by InfoTeddy** [comment]
Oh, right. My `data.zip` doesn't contain levels, so I had to use `-assets` to select a `data.zip` that did - that's probably why I assumed it was a problem with `-assets`.

**Comment by InfoTeddy** [comment]
Well, thinking about it now... it makes perfect sense that `PHYSFS_getRealDir()` of a built-in level is `data.zip`, because that's literally the archive that the level file resides in.

**Comment by flibitijibibo** [comment]
Addressed in https://github.com/TerryCavanagh/VVVVVV/commit/ea74b93f38eddfe87603e92bf838a11598588998. For levels with no custom assets we still need to check and make sure that the level is just a regular old .vvvvvv that's already present in the base filesystem, then we can start loading zipped versions.
