### ISSUE TITLE
[Enhancement] Add some way for changeplayercolour to consistently persist beyond player death

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/VVVVVV#830]
Currently changeplayercolour will always be overridden upon death by the player being changed to the red death colour and then back to the default cyan

**Comment by InfoTeddy** [comment]
I managed to come up with a really simple way to implement this that didn't break backwards compatibility (or forwards compatibility, either, since this is basically purely visual), so this is in 2.4.
