### ISSUE TITLE
Fix VSync renderer workaround

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#831]
Since 2.3 added over-30 mode, the VSync option has been added so people don't run at gazillion FPS. However, SDL works against us by not making it particularly easy to update VSync without restarting the whole game.

The workaround we've done is to tear down everything related to the renderer, which means tearing down the screen texture as well. However, this is bad, because (a) it's only maintainable since most of the rendering is done with CPU-based `SDL_Surface`s and it would be horrible to do if we were to upgrade to SDL_Render in the future, and (b) seems to break terribly on some systems (D3D9, I think?) resulting in a broken screen when people toggle the VSync option, confusing them (and not all of them know they should just close the game and reopen it at this point).

The fix will have to come from SDL's side, with a new VSync API in SDL 2.0.18. Depending on when VVVVVV 2.4 is close to being finished and when SDL 2.0.18 releases, this may need to go in VVVVVV 2.5.

Related: libsdl-org/SDL#4157

**Comment by flibitijibibo** [comment]
We got an approval for the new API, so we just need to finish the SDL side and request a review from either Sam or Ryan (also request a review from me when it's ready, I can be the second vote there).
