### ISSUE TITLE
macOS builds seem to have a dependency problem

### ISSUE THREAD

**Issue by Dav999-v** [TerryCavanagh/VVVVVV#836]
Apparently the macOS version of 2.3 only launches when run from Steam:

![Steam only](https://user-images.githubusercontent.com/44736680/131693095-5c32f77f-14d1-48e6-bdd5-53692bdd7785.png)

I can confirm that both the M&P version and the itch.io version can't be opened due to "a problem" (thanks macOS), and the M&P version also doesn't work for Adr.

This is a part of the crash report for M&P:

![Report](https://user-images.githubusercontent.com/44736680/131694082-eaff889e-a521-4354-b0d1-c1b101b9bf9f.png)

I haven't tried installing SDL, but having to do that would mean VVVVVV can't run out of the box.

**Comment by flibitijibibo** [comment]
Odd, I thought I fixed up the install names... you can fix them with `install_name_tool -change`, it should be `@rpath` instead of /usr/local/lib.

**Comment by flibitijibibo** [comment]
2.3.1 will have this fixed.
