### ISSUE TITLE
Separate interact button option is reversed for (specific?) gamepads

### ISSUE THREAD

**Issue by Fussmatte** [TerryCavanagh/VVVVVV#837]
I've been using a generic PS3 gamepad to play the game. I had the option to have NPC interactions as a separate "E" button enabled (`separate_interact`), but when I set the interact button to Square on my pad, then mashing that same button would trigger the map menu, and then the interaction after it's closed.
If I disable `separate_interact` then the buttons on my gamepad are separated, but not on my keyboard (though mashing Square during a cutscene will still pull up the map menu).

It might be worth noting that I have Steam configured with PlayStation controller support for my PS3 pad (for Big Picture Mode etc), though I don't know if that actually affects the game's controller configuration.

**Comment by InfoTeddy** [comment]
I got out my wired Xbox 360 controller and tested this myself. The interact button seems to function correctly in both cases.

Could you try again, but without Steam?

**Comment by Fussmatte** [comment]
Ahh, this is odd... I launched the game without Steam and the generic PS3 pad ceased to work with it. However, I connected my bluetooth 8bitdo SF30 pad and it works fine. Its behaviour with `separate_interact` also works as it should, unlike the PS3 pad. I'm thinking perhaps there's something quirky with Steam's input stuff, so I'll keep trying things with Steam in the meantime.

**Comment by flibitijibibo** [comment]
Throwing gamecontrollerdb.txt in the game root may fix the offline PS3 support:

https://github.com/gabomdq/SDL_GameControllerDB

**Comment by Fussmatte** [comment]
> 
> 
> Throwing gamecontrollerdb.txt in the game root may fix the offline PS3 support:
> 
> https://github.com/gabomdq/SDL_GameControllerDB

It doesn't do anything for me. I think I might have some weird local PS3 driver issues. I'm still figuring this all out in the meantime.

**Comment by Fussmatte** [comment]
Well something's screwed up with either ScpToolkit or my PS3 pad. I've tried several things and it simply will not stop vibrating, and Steam won't pick it up anymore, so I can't test anything further. The original problem might be related to it being a generic and obscure controller anyway, so I'm gonna close this for now.
