### ISSUE TITLE
MMMMMM music pack not working

### ISSUE THREAD

**Issue by Some1NamedNate** [TerryCavanagh/VVVVVV#857]
I tried to load the music pack file that came with FamilyJules and SoulEye's album "MMMMMM" into VVVVVV and it doesn't work. Its location is %UserProfile%\Documents\VVVVVV\levels\mmmmmm.vvv

**Comment by InfoTeddy** [comment]
It needs to be inside `VVVVVV`, not `VVVVVV\levels`.
