### ISSUE TITLE
"The application was unable to start correctly (0xc000007b)" on Windows 10

### ISSUE THREAD

**Issue by Dav999-v** [TerryCavanagh/VVVVVV#861]
Someone on the VVVVVV Discord (Doom BOY) reported getting "The application was unable to start correctly (0xc000007b)" with the official Make and Play package.

`0xc000007b` seems to mean something with mixing 32-bit and 64-bit versions of DLLs, but after he tried some different builds, it appears that VS2019 ones appear to work for him while VS2010 ones don't, even when they use the same DLLs. I can't reproduce this problem myself - for me, all these builds work.

In particular, I compiled this version with VS2010 and it gave him the same error:
https://cdn.discordapp.com/attachments/342372109994950659/936795855141371954/VVVVVV-MP-2.3.6-2022-01-29.zip
(I added the SDL 2.0.20 DLL to this)

Then I used VS2019 to compile, and it started working:
https://cdn.discordapp.com/attachments/342372109994950659/936800083830263868/VVVVVV-MP-2.3.6-2022-01-29-VS2019.zip

In my VS2019 build, I copied all DLLs from the official Make and Play package, so the only difference that made it work is that the binary was compiled with VS2019 instead of VS2010.

(An old interim version of 2.3 M&P I had released before 2.3 came out (https://github.com/Dav999-v/VVVVVV/releases) also worked, I don't remember the fine details on those builds though - the latest one was from some CI which probably used VS2019 as well)

**Comment by flibitijibibo** [comment]
Sounds like there's just a redist issue - they may need to reinstall the x86 binaries?
