### ISSUE TITLE
Steam Deck review

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#866]
VVVVVV received its Steam Deck review! Here it is:

![image](https://user-images.githubusercontent.com/2874150/154039046-7f70c03f-f5e9-435e-951c-f87c270e99fe.png)

We got a "Playable" score, which is fine - most games on steam will get this, I think. We passed all the checks apart from "Controller Glyphs":

>Test failed due to to mouse / keyboard input glyphs being shown. We highly encourage only showing input glyphs for the active devices and not showing mouse / keyboard prompt unless a gamepad is not plugged in, or a mouse / keyboard action was activated by the user. If your game has controller support this may be due to assets with hard-coded glyphs or the Steam Deck's trackpad/gyro input being sent to the game mouse movement. For games under active development we highly encourage supporting mouse-style aim from controllers and to only change to mouse/kb glyphs on mouse click or keyboard press events. For older titles you can also fix this issue by going to the Steam Input settings section of the partner site and setting your default configuration to either the "Gamepad w/ Camera Controls" template for 1st/3rd person games or "Gamepad" template for platformer and sports games. The title was found to only feature mouse / keyboard glyphs across all areas of the title. 

If there's any interest in going for a "verified" score, that'd be nice to have - but not essential. The game runs fine on the Steam Deck, after all.

Time-wise; this review is "pending" for one week, and then after that will be displayed publicly on the store page. We have the option to rush out a fix and apply for new test before that happens if we like.

More realistically, it'll still be a while before Steam Decks start getting shipped out, so we could maybe just tack this issue on to the 2.4 to do list?

**Comment by TerryCavanagh** [comment]
Oh, as an aside, this was unexpected:

![image](https://user-images.githubusercontent.com/2874150/154040136-1167d606-60f2-4613-b630-8d12dd287055.png)

We have a native Linux port, so I didn't expect to see this Proton recommended runtime?

**Comment by flibitijibibo** [comment]
What in the world...? Did they explain why, at all? Are we even getting a chance to override this as the authors?

**Comment by flibitijibibo** [comment]
Alrighty, thanks - pretty sure I'm watching my job go up in flames though 💀

The main thing to get past cert is the action set issue, which should come as part of the localization update. 2.4 should be able to pass cert!

**Comment by TerryCavanagh** [comment]
Yikes!

Here's what I've sent through the online portal, will report back when I get a reply!

![image](https://user-images.githubusercontent.com/2874150/154087199-7cf92f4a-6d60-4cf0-b43d-d69999fb4369.png)

**Comment by flibitijibibo** [comment]
We've been told to resubmit - seems the process was originally done in such a way that native wasn't being tested first? Weird considering we didn't even have cert access just recently so it must have been backlogged or something.

Dicey should also get resubmitted, same issue was found with that game too.

**Comment by serebit** [comment]
Yeah, they updated the process to test native first after some feedback. Don't worry, @flibitijibibo, your job is safe— *for now* 😛

**Comment by flibitijibibo** [comment]
"After some feedback" 🙄

Just An Experiment Bro aside, we should resubmit again when 2.4 is in beta status.

**Comment by Weetile** [comment]
![image](https://user-images.githubusercontent.com/7700383/155387113-baf1f03e-b520-4a04-94f1-49a47a95106c.png)
This might be useful? Found on the Steam Deck Discord

**Comment by TerryCavanagh** [comment]
Updates!

![image](https://user-images.githubusercontent.com/2874150/155946197-fbee0716-87b9-4870-81fb-103ce0440d7c.png)

We got a �!

Looks like they fixed the native build issue:

![image](https://user-images.githubusercontent.com/2874150/155946374-f8349124-2124-4195-972e-36277e999cd7.png)

**Comment by InfoTeddy** [comment]
A missing Unicode character? Better than recommending Proton, I suppose...

**Comment by Weetile** [comment]
What does � mean? Is that Verified or Playable?

**Comment by flibitijibibo** [comment]
It's playable - it'll be verified when the input prompts are fixed.

**Comment by TerryCavanagh** [comment]
With the new steam beta, I can apply for a re-review. I think we should get a pass without much difficulty!

**Comment by flibitijibibo** [comment]
Sounds good, as soon as we're in Release Candidate mode I'll rebuild and submit! (We still have zero control over when results get published so we can't submit too early...)

**Comment by flibitijibibo** [comment]
The 2.4 beta passed, so this is complete!
