### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by Fancy2209** [TerryCavanagh/VVVVVV#873]
Hello, I decided to try to build VVVVVV but when I run make it fails
```
[  9%] Built target faudio-static
-- This is interim commit e47781f (committed 2022-03-31)
[  9%] Built target GenerateVersion
[ 12%] Built target lodepng-static
[ 16%] Built target tinyxml2-static
[ 33%] Built target physfs-static
Consolidate compiler generated dependencies of target VVVVVV
[ 35%] Building CXX object CMakeFiles/VVVVVV.dir/src/Graphics.cpp.o
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp: In member function ‘void Graphics::do_print(int, int, const string&, int, int, int, int, int)’:
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp:524:9: error: ‘SDL_clamp’ was not declared in this scope; did you mean ‘SDL_wcscmp’?
  524 |     r = SDL_clamp(r, 0, 255);
      |         ^~~~~~~~~
      |         SDL_wcscmp
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp: In member function ‘bool Graphics::next_wrap(size_t*, size_t*, const char*, int)’:
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp:594:13: error: ‘SDL_FALLTHROUGH’ was not declared in this scope
  594 |             SDL_FALLTHROUGH;
      |             ^~~~~~~~~~~~~~~
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp:593:20: error: this statement may fall through [-Werror=implicit-fallthrough=]
  593 |             *start += 1;
      |             ~~~~~~~^~~~
/home/paulo/VVVVVV/desktop_version/src/Graphics.cpp:595:9: note: here
  595 |         case '\0':
      |         ^~~~
cc1plus: some warnings being treated as errors
make[2]: *** [CMakeFiles/VVVVVV.dir/build.make:174: CMakeFiles/VVVVVV.dir/src/Graphics.cpp.o] Erro 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/VVVVVV.dir/all] Erro 2
make: *** [Makefile:91: all] Erro 2
```
What am I doing wrong?

**Comment by InfoTeddy** [comment]
Your SDL is too old.

**Comment by Fancy2209** [comment]
Oh, I wished 21.10 wouldn't do that
Last time I tried to build SDL it was weird, do I really need to either use homebrew or compile from source? the ppa on the linked issue isn't avaliable on 21.10

**Comment by InfoTeddy** [comment]
Yes, those are your other two options. Why doesn't the PPA work? Is it some weird Pop_OSism?

**Comment by Fancy2209** [comment]
No
The PPA doesn't support impish (21.10) it seems

**Comment by Fancy2209** [comment]
No
The PPA doesn't support impish (21.10) it seems

**Comment by Fancy2209** [comment]
Just confirmed
The PPA is only for LTS versions
21.10 isn't a LTS

**Comment by InfoTeddy** [comment]
That's unfortunate.

Again, your two options now are to install Homebrew or to compile SDL from source.

**Comment by Dav999-v** [comment]
It may be that you can install the PPA for an LTS version anyway; I've used mismatching PPA versions before, and it probably can't hurt to try.

**Comment by Fancy2209** [comment]
It works since I upgraded to 22.04
Should've said that

**Comment by Dav999-v** [comment]
It looks like 22.04 has SDL 2.0.20 in the standard repos, which is recent enough for VVVVVV right now.

However, unless anything changed, features from the latest SDL (currently 2.0.22) are usually adopted in VVVVVV without any hesitation, so this problem will probably reappear at some point unless you use the PPA or one of the other methods of installing SDL.
