### ISSUE TITLE
Found a glitch that happens when saving the game at a specific point in the game

### ISSUE THREAD

**Issue by Kokasgui** [TerryCavanagh/VVVVVV#879]
Hi! Basically I found a glitch when saving the game right after playing the Gravitron portion of the game without touching the checkpoint. And then I went exploring ahahah

The video below explains almost everything I found about this bug but I forgot to say some things:

- The footage is at 60 fps (the edited video is at 30 fps). I don't know if it's important or not but I might as well say it
- When loading the save file you can flip immedeately and avoid falling/going up, starting the Gravitron right away. For some reason it's way easier to flip without Flip Mode activated (at least in my opinion)
- After falling/going up you can warp normally like usually and go to the room you first spawn when playing this intermission

https://user-images.githubusercontent.com/91392390/166337578-ec24152d-3aa8-48e9-b31e-c2cfa82c6d84.mp4

**Comment by InfoTeddy** [comment]
Yes, this is a bug. But it's a bug that speedrunners use to glitch out of bounds and complete the game early. (They press R instead of save+quitting, though.) So it won't be fixed.

**Comment by Kokasgui** [comment]
Oh okay didn't know that. Thanks for clearing that up!
