### ISSUE TITLE
Broken links on thelettervsixtim.es

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/VVVVVV#881]
![image](https://user-images.githubusercontent.com/2874150/172143371-e545e4ac-0fef-463c-b41c-2c235fc50a81.png)

**Comment by flibitijibibo** [comment]
The README needs an update too, still links to a MadTracker subdomain...

**Comment by Fancy2209** [comment]
lemming.seri.ce are also busted
Wich means that the downloads on https://thelettervsixtim.es/demo.html are broken
Would Probably be a better idea to just offer the download of the Demo SWF instead of packaged versions of it, still just a suggestion

**Comment by TerryCavanagh** [comment]
I did a quick pass through the website and fixed all the broken links I could find. All but one of the review links were broken now, grim!

The demo page maybe needs to be reconsidered at some point, now that flash isn't a thing, but for now, it's ok.

**Comment by Fancy2209** [comment]
> I did a quick pass through the website and fixed all the broken links I could find. All but one of the review links were broken now, grim!
> 
> The demo page maybe needs to be reconsidered at some point, now that flash isn't a thing, but for now, it's ok.

There are flash emulators like Ruffle and AwayFL
Don't know if any of them can run VVVVVV tough

**Comment by InfoTeddy** [comment]
> > I did a quick pass through the website and fixed all the broken links I could find. All but one of the review links were broken now, grim!
> > The demo page maybe needs to be reconsidered at some point, now that flash isn't a thing, but for now, it's ok.
> 
> There are flash emulators like Ruffle and AwayFL Don't know if any of them can run VVVVVV tough

Or we could make a new demo version out of the C++ version, since it supports WebASM now (which runs on HTML5/JavaScript).

**Comment by TerryCavanagh** [comment]
> There are flash emulators like Ruffle and AwayFL Don't know if any of them can run VVVVVV tough

I'd be shocked - these projects are only just starting to introduce AS3 support, so it'll probably be a long time before that happens.
 
> Or we could make a new demo version out of the C++ version, since it supports WebASM now (which runs on HTML5/JavaScript).

Ahhh, it's a nice idea in a way, for completeness sake, but I think it's probably not worth the extra work at this point in the game's life. The amount of people who would actually play it would be pretty minimal, probably.

**Comment by Fancy2209** [comment]
AwayFL Supports AS3 since 2020!
Tough I don't know if VVVVVV would fully work
https://awayfl.org/

A quarta, 14/09/2022, 08:07, Terry Cavanagh ***@***.***>
escreveu:
