### ISSUE TITLE
Update Maddy Thorson's name in built-in level

### ISSUE THREAD

**Issue by Fussmatte** [TerryCavanagh/VVVVVV#893]
“Vertex Vortex” still lists her deadname under the author field

**Comment by TerryCavanagh** [comment]
Ahh, this is tricky - Vertex Vortex is in `data.zip`, which ideally I'd like to never have to change.

Maybe there's a solution to this that doesn't involved an update to the data.zip file? Something hardcoded in the custom level menu, maybe?

**Comment by InfoTeddy** [comment]
We could just load in another zip that takes priority over `data.zip`.

**Comment by Fussmatte** [comment]
Like mentioned in the Discord, updating `data.zip` probably isn't a big problem here, since the main part of that is making sure different `data.zip` versions don't break with different versions of the game.

I also kind of don't like the idea of updating it via `game.zip` since the deadname would still be present, just overriden. And although that might not actually be a big problem depending on how you look at it, well, updating `data.zip` quietly (as Terry suggested on Discord) is probably fine.

**Comment by TerryCavanagh** [comment]
Yeah, on reflection, it's fine to just update `data.zip` because that won't break any existing things. I'll add that to my to-do list and do it soon!

**Comment by TerryCavanagh** [comment]
Ok, `data.zip` and the corresponding mobile data file have been updated on the server - these will be the new data files as of the next version.

**Comment by TerryCavanagh** [comment]
Updated both data files again to fix the website url too.
