### ISSUE TITLE
[Question] What is the preferred indentation style

### ISSUE THREAD

**Issue by chrboe** [TerryCavanagh/VVVVVV#9]
I can't help but notice that the code base has a mix of tabs and 4 spaces based indentation. I realize you don't want to take formatting patches, but what is the preferred indentation style to use when submitting a patch?

**Comment by flibitijibibo** [comment]
The preferred style is essentially whatever the style is for the code surrounding the changes, so it's possible a patchset may have both types of indentation.

(Historically, I think a good chunk of it started as spaces, but a lot of it ended up being tabs as well. All the new stuff I wrote for 2.2 was definitely tabs, and I'm sure I accidentally did tabs in files where it should have been spaces.)

**Comment by akien-mga** [comment]
@flibitijibibo Since the repo doesn't come with extensive Git history that formatting changes would mess up, I'd suggest picking one indent style and run a quick script to adjust all indentation to that style.

Currently it can be quite misleading, to the point that GCC throws warnings about it (`-Wall -Werror`):
```
[ 36%] Building CXX object CMakeFiles/vvvvvv.dir/src/GraphicsUtil.cpp.o
/usr/bin/c++  -DPHYSFS_SUPPORTS_DEFAULT=0 -DPHYSFS_SUPPORTS_ZIP=1 -I/home/akien/tmp/VVVVVV/desktop_version/src -I/home/akien/tmp/VVVVVV/desktop_version/tinyxml -I/home/akien/tmp/VVVVVV/desktop_version/physfs -I/home/akien/tmp/VVVVVV/desktop_version/lodepng -I/usr/include/SDL2  -Wall -Werror   -o CMakeFiles/vvvvvv.dir/src/GraphicsUtil.cpp.o -c /home/akien/tmp/VVVVVV/desktop_version/src/GraphicsUtil.cpp
/home/akien/tmp/VVVVVV/desktop_version/src/GraphicsUtil.cpp: In function ‘SDL_Surface* ScaleSurfaceSlow(SDL_Surface*, int, int)’:
/home/akien/tmp/VVVVVV/desktop_version/src/GraphicsUtil.cpp:193:2: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
  for(Sint32 y = 0; y < _surface->h; y++)
  ^~~
/home/akien/tmp/VVVVVV/desktop_version/src/GraphicsUtil.cpp:203:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   return _ret;
   ^~~~~~
```

**Comment by flibitijibibo** [comment]
I'd be willing to fix the ones that fail `-Wall -Werror`, at least.
