### ISSUE TITLE
default keyboard and controller bindings

### ISSUE THREAD

**Issue by cjfp** [TerryCavanagh/VVVVVV#920]
My gamepad isn't compatible (it's a Switch SNES controller), so I'm trying to create a mapping with JoyToKey.  My questions are:

1) What is the keyboard binding for Interact?

2) Is the following table otherwise correct and complete?  

```
         Keys, Buttons, Command
Space | V | Z,       A, Action | Flip
       Escape,       B, Menu
          ???,       X, Interact
        Enter,       Y, Enter
            R,      RB, Restart
            M,     n/a, Mute Everything
            N,     n/a, Mute Only Music
           Up,      Up, Up | Flip
         Down,    Down, Down | Flip
         Left,    Left, Left
        Right,   Right, Right
```

Thanks!

**Comment by InfoTeddy** [comment]
Interact is E only if you have it enabled in options (options -> gameplay -> speedrun options -> interact button). Otherwise, Enter is used. And yes, the table looks complete.

By the way, input rebinding is planned for 2.4 so you won't need to use a third-party program like JoyToKey.

**Comment by InfoTeddy** [comment]
Ok, I missed that your gamepad wasn't compatible. Maybe you could drop a [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt) next to the game executable? I see a lot of SNES and Switch controllers in there, that's probably better than using JoyToKey.

**Comment by cjfp** [comment]
Thanks for checking and filling in re: Interact.

I tried your suggestion to use gamecontrollerdb.txt but it doesn't work for me.  JoyToKey 5.2.1 is really pretty good once it's set up.  I have it set now to switch to the VVVVVV bindings when the game launches.  I have to do this for a lot of games, but I'm willing to tolerate it given how much I like the controller.  There is an XInput wrapper that someone wrote but it introduces other problems, like switching the buttons around.  

Anyway, I'm happy!
