### ISSUE TITLE
Trinket Overlay won't go away if warped to ship

### ISSUE THREAD

**Issue by NightScript370** [TerryCavanagh/VVVVVV#921]
Interesting bug I encountered due to a misunderstanding on my part.
![Screencast from 2023-01-02 13-43-43.webm](https://user-images.githubusercontent.com/18664762/210269237-c7c5e826-3e14-4099-a8fb-2e4a32d69d0f.webm)

To reproduce this, get a trinket, go to the map menu, hit right, warp back to ship and try to hit the action button.
I am on Ubuntu 22.04 using the latest version on Steam at the time of writing this

**Comment by InfoTeddy** [comment]
The text boxes will go away if you die, but the cutscene bars won't unless you activate a cutscene.

**Comment by NightScript370** [comment]
I worked around it by just exiting and re-entering the game (like classic tech support would ask), but it might be worthwhile to close the trinket menu when the map menu is entered.
