### ISSUE TITLE
Returning from invincibility/slowdown menus puts you one menu option above the menu option you selected before

### ISSUE THREAD

**Issue by InfoTeddy** [TerryCavanagh/VVVVVV#94]
Looks like this started happening after the text outline accessibility option was added in 6e9712f113388af4e3711773555e55c8620102b1.

**Comment by flibitijibibo** [comment]
Probably need to increment the selector by 1 in those menus’ return buttons, hopefully a 1-liner each?

**Comment by flibitijibibo** [comment]
https://github.com/TerryCavanagh/VVVVVV/commit/134a0f10700fd5dd47dcf5a844259ad3043ff115
