### ISSUE TITLE
Provide an option to unbundle tinyxml, physfs, and lodepng

### ISSUE THREAD

**Issue by fuzxxl** [TerryCavanagh/VVVVVV#95]
Right now, VVVVVV comes with its own copies of tinyxml, physfs, and lodepng.  It would be nice if there was a switch in the CMakeLists.txt to replace these with the operating system's versions if desired.  This reduces binary sizes and allows VVVVVV to take advantage of library updates delivered by the operating system's own package management.

**Comment by flibitijibibo** [comment]
Is an operating system really packaging lodepng...? In any case, this is something only repositories care about, and we aren't targeting distribution for repositories.

**Comment by fuzxxl** [comment]
I'm unaware of any system packaging lodepng, but tinyxml and physfs are definitely available on various systems.  I do understand your concerns though.

**Comment by flibitijibibo** [comment]
For now we're going to stick with static libraries - #20 may be of interest to you though.

**Comment by fuzxxl** [comment]
I wasn't suggesting to drop the static libraries, just to provide an option to use the system's libraries instead using a compile time option.  However, I understand your decision.
