### ISSUE TITLE
Some sound effects still don't play properly

### ISSUE THREAD

**Issue by Dav999-v** [TerryCavanagh/VVVVVV#953]
As described in ba7519106fc805cc6ce277b18401e1bcecc03ec9 (which fixed #900):

> Also also, some OGG files don't work with this. Namely, ones produced by FFmpeg.

I tested this to verify (`ffmpeg -i terminal.wav terminal.ogg`), and indeed, this .ogg (renamed to .wav) makes a weird static noise, but I think the original terminal sound is still in it, but lower-pitched. However, the same .ogg does work as music, so there still appears to be something different about OGG sound effects being loaded compared to music.

(mild volume warning)

https://user-images.githubusercontent.com/44736680/226205417-52f25052-9862-464f-925a-2cff78c73220.mp4

**Comment by AllyTally** [comment]
It seems like OGG sound effects which DO play properly cut off after a few seconds, at least when exported from FL Studio.

**Comment by AllyTally** [comment]
It looks like a WAV file I have doesn't play properly anymore as well...

[Volume warning, VERY LOUD] Video:

https://user-images.githubusercontent.com/19293054/227740059-ca1181c8-596a-4458-8f91-0ef8ca5f6fab.mp4

[Here](https://files.catbox.moe/5c68jq.wav) is the file.

**Comment by Dav999-v** [comment]
It seems like, at least partially, another "voice was already initialized" problem - if I change the hardcoded `format.wBitsPerSample = 16;` in `SoundTrack::Init()` to 8, that sound effect sounds correct, and everything else sounds slowed down. The assignments to `format` attributes in `SoundTrack::LoadWAV()` (and I'm guessing `SoundTrack::LoadOGG()` too) have no effect.
