### ISSUE TITLE
Make NO_EDITOR a runtime option

### ISSUE THREAD

**Issue by flibitijibibo** [TerryCavanagh/VVVVVV#992]
We pretty much have a "no editor" mode already, but it's done as a build-time option. Eventually the editor might be usable outside of PC, but for platforms like Deck where it depends on the current OS mode being used it helps to be able to support hiding the editor at runtime.

AFAIK this option is basically a subset of NO_CUSTOM_LEVELS, so it shouldn't interfere with existing builds _too_ much, it just means builds with custom levels that don't want the editor will just be hiding it instead of stripping it out entirely (and users can bring it back if they really really want to).

**Comment by Dav999-v** [comment]
Would this mean the editor will be completely hidden on Deck (as opposed to displaying an error or being grayed out)?

**Comment by flibitijibibo** [comment]
If we can make use of the existing `#define OFFSET` trickery it'd be great to have it be _totally_ hidden, but I have definitely gotten other titles through cert by having a simple messagebox instead (Gateways is the last example I can think of).
